Repository asyncapi/website, pull requests merged in 2022-11, with the labels that each got.

#1069 fix: update lint-pr-title.yml
  .github/workflows/lint-pr-title.yml
Labels: ready-to-merge

#1066 fix: disable cache in frontMatter to avoid mix duplicated contents
  scripts/build-post-list.js
Labels: ready-to-merge

#1070 feat: add conference banner with YT livestream
  components/Hero.js
  components/campaigns/AnnoucementHero.js
  components/layout/BlogLayout.js
  components/layout/Container.js
  components/layout/DocsLayout.js
  components/layout/GenericLayout.js
  pages/blog/index.js
  pages/jobs/index.js
Labels: enhancement, ready-to-merge

#1076 feat: add nav banner for conference 2022
  components/campaigns/AnnoucementHero.js
  components/campaigns/Banner.js
  components/campaigns/Banner.jsx
Labels: enhancement, ready-to-merge

#1081 fix: producer page wrong link
  pages/docs/concepts/channel.md
  pages/docs/concepts/consumer.md
  pages/docs/concepts/producer.md
  pages/docs/tutorials/index.md
Labels: 🐞 docs bug, area/docs

#1077 fix: homepage link to studio not matching asyncapi version
  components/buttons/OpenInStudioButton.js
Labels: bug, ready-to-merge, area/javascript

#1074 docs: update the Bump.sh brand
  pages/docs/tools/index.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#1087 fix: enable ids in list of features from landing page
  components/features/index.jsx
  components/typography/TextLink.js
Labels: ready-to-merge

#1100 docs: update the buttons for the channel page doc
  pages/docs/concepts/channel.md
Labels: ready-to-merge, 🐞 docs bug, area/docs, gsod

#1102 docs: update index.md tutorial-overview buttons
  pages/docs/tutorials/index.md
Labels: ready-to-merge, 🐞 docs bug, area/docs, gsod

#1106 docs: fix the bug in button display section
  pages/docs/concepts/consumer.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#1108 fix: dashboard improvement
  components/dashboard/Header.js
  dashboard.json
  scripts/dashboard/build-dashboard.js
Labels: ready-to-merge

#756 docs: fix invalid links in markdown files
  README.md
  mlc_config.json
  pages/about/index.md
  pages/blog/2021-summary.md
  pages/blog/2022Q1-summary.md
  pages/blog/april-2021-at-asyncapi.md
  pages/blog/async-api-spec-3.0-release.md
  pages/blog/async_standards_compare.md
  pages/blog/asyncapi-discovery-intro.md
  pages/blog/asyncapi-github-actions.md
  pages/blog/asyncapi_codegen_scst.md
  pages/blog/automated-releases.md
  pages/blog/february-2021-at-asyncapi.md
  pages/blog/google-season-of-docs-2022.md
  pages/blog/governance-motivation.md
  pages/blog/hackathon-faq.md
  pages/blog/hacktoberfest-2020.md
  pages/blog/json-schema-beyond-validation.md
  pages/blog/july-december-2021-at-asyncapi.md
  pages/blog/march-2021-at-asyncapi.md
  pages/blog/may-2021-at-asyncapi.md
  pages/blog/microcks-asyncapi-part1.md
  pages/blog/openapi-vs-asyncapi-burning-questions.md
  pages/blog/openforce-2022.md
  pages/blog/release-notes-2.2.0.md
  pages/blog/release-notes-2.3.0.md
  pages/blog/release-notes-2.5.0.md
  pages/blog/status-update-27-20.md
  pages/blog/status-update-29-20.md
  pages/blog/status-update-31-20.md
  pages/blog/status-update-33-20.md
  pages/blog/status-update-37-20.md
  pages/blog/status-update-39-20.md
  pages/blog/status-update-41-20.md
  pages/blog/status-update-43-20.md
  pages/blog/status-update-47-20.md
  pages/blog/status-update-week-14-2019.md
  pages/blog/status-update-week-15-2019.md
  pages/blog/using-nunjucks-with-asyncapi.md
  pages/blog/websocket-part1.md
  pages/blog/websocket-part2.md
  pages/docs/reference/specification/v2.0.0.md
  pages/docs/reference/specification/v2.1.0.md
  pages/docs/reference/specification/v2.2.0.md
  pages/docs/reference/specification/v2.3.0.md
  pages/docs/reference/specification/v2.4.0.md
  pages/docs/tutorials/getting-started/security.md
  pages/docs/tutorials/streetlights-interactive.md
  pages/jobs/head-of-dx-upvest.md
  pages/jobs/ui-ux-dx-designer.md
Labels: ready-to-merge

#1128 ci: improve logging for tools build script
  .github/workflows/regenerate-tools.yml
  scripts/tools/tools-object.js
Labels: ready-to-merge
