Repository asyncapi/website, pull requests merged in 2022-10, with the labels that each got.

#997 feat: add guides bucket
  components/docs/DocsCards.js
  components/icons/Guide.js
  components/navigation/DocsNav.js
  components/navigation/learningItems.js
  pages/docs/guides/_section.md
  pages/docs/guides/index.md
  pages/docs/reference/_section.md
Labels: enhancement, ready-to-merge, area/docs, gsod

#1003 fix: remove unnecessary step in Streetlights tutorial
  pages/docs/tutorials/streetlights.md
Labels: ready-to-merge

#939 feat: tools backend implementation
  .github/workflows/regenerate-tools.yml
  config/tools-automated.json
  config/tools-manual.json
  config/tools.json
  package-lock.json
  package.json
  scripts/build-tools.js
  scripts/tools/categorylist.js
  scripts/tools/combine-tools.js
  scripts/tools/extract-tools-github.js
  scripts/tools/tags-color.js
  scripts/tools/tools-object.js
  scripts/tools/tools-schema.json
Labels: ready-to-merge

#1011 fix: solve Windows build error
  scripts/build-post-list.js
Labels: ready-to-merge

#1020 fix: correct the links of navigation buttons in Docs #1014
  pages/docs/concepts/index.md
  pages/docs/concepts/producer.md
  pages/docs/concepts/server.md
  pages/docs/guides/index.md
  pages/docs/index.md
  pages/docs/reference/index.md
  pages/docs/tools/index.md
  pages/docs/tutorials/getting-started/asyncapi-documents.md
  pages/docs/tutorials/getting-started/coming-from-openapi.md
  pages/docs/tutorials/getting-started/event-driven-architectures.md
  pages/docs/tutorials/getting-started/hello-world.md
  pages/docs/tutorials/getting-started/index.md
  pages/docs/tutorials/getting-started/security.md
  pages/docs/tutorials/getting-started/servers.md
  pages/docs/tutorials/index.md
  pages/docs/tutorials/streetlights-interactive.md
  pages/docs/tutorials/streetlights.md
Labels: 🐞 docs bug, area/docs

#991 docs: add new consumer concept doc
  pages/docs/concepts/consumer.md
Labels: 📑 docs, area/docs, gsod

#973 docs: fix capitalization: Github -> GitHub, Javascript -> JavaScript, OpenApi -> OpenAPI
  CONTRIBUTING.md
  README.md
  components/buttons/GitHubIssue.js
  components/buttons/GithubButton.js
  components/layout/DocsLayout.js
  components/navigation/NavBar.js
  components/navigation/communityItems.js
  components/navigation/toolingItems.js
  netlify/edge-functions/serve-definitions.ts
  pages/blog/an-api-strategist-explores-event-driven-apis.md
  pages/blog/asyncapi-and-apicurio-for-asynchronous-apis.md
  pages/blog/asyncapi-github-actions.md
  pages/blog/intent-driven-api.md
  pages/blog/mistake-odyssey.md
  pages/blog/radical-transparency.md
  pages/blog/release-notes-2.3.0.md
  pages/blog/release-notes-2.4.0.md
  pages/blog/understanding-asyncapis.md
  pages/community/tsc.js
  pages/docs/tools/index.md
  pages/docs/tutorials/streetlights.md
  pages/jobs/dev-rel-postman.md
  pages/jobs/ui-ux-dx-designer.md
  pages/roadmap.js
  pages/tools/github-actions.js
Labels: ready-to-merge

#1026 feat: add subscribe form to meetings and tsc page
  components/NewsletterSubscribe.js
  pages/blog/2020-summary.md
  pages/blog/asyncapi-partners-with-postman.md
  pages/community/meetings.js
  pages/community/tsc.js
  pages/index.js
  pages/newsletter/index.js
Labels: ready-to-merge

#1044 fix: subscribe forms
  components/NewsletterSubscribe.js
Labels: ready-to-merge

#514 feat: add dashboard on the website
  .github/workflows/regenerate-meetings-and-videos.yml
  .gitignore
  components/buttons/GithubButton.js
  components/buttons/SlackButton.js
  components/dashboard/Button.js
  components/dashboard/GoodFirstIssues.js
  components/dashboard/GoodFirstIssuesTip.js
  components/dashboard/Header.js
  components/dashboard/table/Filters.js
  components/dashboard/table/Pagination.js
  components/dashboard/table/Row.js
  components/dashboard/table/Table.js
  components/icons/Dashboard.js
  components/icons/Slack.js
  components/navigation/communityItems.js
  dashboard.json
  package-lock.json
  package.json
  pages/community/dashboard.js
  public/img/illustrations/icons/arrow.svg
  public/img/illustrations/icons/close-icon.svg
  public/img/illustrations/icons/filters-icon.svg
  public/img/illustrations/icons/fire.svg
  public/img/illustrations/icons/issue.svg
  public/img/illustrations/icons/pull-request.svg
  public/img/illustrations/icons/tip-icon.svg
  scripts/dashboard/build-dashboard.js
  scripts/dashboard/issue-queries.js
  styles/globals.css
Labels: ready-to-merge

#1047 feat: implementation of lazy loading on Blog page (#937)
  components/AuthorAvatars.js
  components/navigation/BlogPostItem.js
Labels: ready-to-merge, autoupdate

#1062 ci: remove not needed workflow
  .github/workflows/if-go-pr-testing.yml
Labels: ready-to-merge
