Repository asyncapi/website, pull requests merged in 2022-05, with the labels that each got.

#718 fix: make tools generator page responsive
  components/layout/Container.js
Labels: ready-to-merge

#699 fix: alternative text accessibility issues on AsyncAPI website
  components/AsyncAPILogo.js
  components/Footer.js
  components/GoldSponsors.js
  components/Hero.js
  components/Sponsors.js
  components/SupportUs.js
  components/Testimonial.js
  components/buttons/Button.js
  components/campaigns/AnnoucementHero.js
  components/navigation/NavBar.js
  components/slack/Message.js
  components/slack/index.js
  css/styles.css
  package-lock.json
  pages/_app.js
  pages/_document.js
  pages/blog/index.js
  pages/index.js
Labels: ready-to-merge, autoupdate, a11y, area/a11y

#739 fix: join us button width on mobile device
  package-lock.json
  pages/index.js
Labels: ready-to-merge

#744 fix: changed the cta bg and text color
  components/campaigns/Banner.jsx
  components/navigation/NavBar.js
Labels: ready-to-merge

#760 ci: modify regenerate meetings workflow to not trigger on forks
  .github/workflows/regenerate-meetings.yml
Labels: ready-to-merge

#764 ci: fix indent in workflow for meetings
  .github/workflows/regenerate-meetings.yml
Labels: ready-to-merge

#767 ci: fixed the cron syntax error in the workflow
  .github/workflows/regenerate-meetings.yml
Labels: ready-to-merge

#773 fix: use right semantic tags on homepage
  components/Calendar.js
  components/Footer.js
  components/Hero.js
  components/Sponsors.js
  components/Testimonial.js
  components/features/index.jsx
  components/layout/Container.js
  components/navigation/BlogPostItem.js
  pages/blog/index.js
  pages/index.js
Labels: ready-to-merge

#731 fix: scroll margin in the TOC
  css/styles.css
  postcss.config.js
Labels: ready-to-merge, autoupdate

#777 fix: testimonial section
  components/Testimonial.js
  pages/index.js
Labels: ready-to-merge

#770 fix: update 2022Q1-summary.md
  pages/blog/2022Q1-summary.md
Labels: ready-to-merge

#663 chore(blog): announcing AsyncAPI & Spectral collaboration
  pages/blog/creating-consistency-announcing-asyncapi-spectral-together.md
  public/img/avatars/jrozek.webp
  public/img/posts/creating-consistency-announcing-asyncapi-spectral-together/cover.webp
  public/img/posts/creating-consistency-announcing-asyncapi-spectral-together/lint-results.webp
Labels: ready-to-merge

#723 docs: refactor content in channel section under event driven architecture
  pages/docs/getting-started/event-driven-architectures.md
Labels: ready-to-merge

#783 docs: add compare tools section to tooling page (tooling.md)
  pages/docs/community/tooling.md
Labels: ready-to-merge

#737 chore: blog typo fix
  pages/blog/google-season-of-docs-2022.md
Labels: ready-to-merge

#726 docs: improve content in Message section of EDA
  pages/docs/getting-started/event-driven-architectures.md
Labels: ready-to-merge
