Repository asyncapi/website, pull requests merged in 2022-12, with the labels that each got.

#1135 feat: support yaml as format for `.asyncapi-tools`
  config/tools-automated.json
  config/tools-manual.json
  config/tools.json
  package-lock.json
  package.json
  scripts/build-tools.js
  scripts/tools/categorylist.js
  scripts/tools/combine-tools.js
  scripts/tools/tools-object.js
  scripts/tools/tools-schema.json
Labels: ready-to-merge

#1013 docs: add protocol concepts doc
  pages/docs/concepts/protocol.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#992 docs: new concept doc (application)
  pages/docs/concepts/application.md
  pages/docs/concepts/channel.md
  pages/docs/concepts/message.md
  pages/docs/concepts/protocol.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#1137 feat: added new md component
  components/MDX.js
  components/Profile.js
Labels: ready-to-merge

#1143 chore: add more categories for tools and support repo description
  config/tools-automated.json
  config/tools-manual.json
  config/tools.json
  scripts/tools/categorylist.js
  scripts/tools/tools-object.js
  scripts/tools/tools-schema.json
Labels: ready-to-merge

#1147 fix: changed og_image
  public/img/social/website-card.jpg
Labels: ready-to-merge

#1131 feat: hacktoberfest Blog Post
  pages/blog/hacktoberfest-2022.md
  public/img/avatars/ace.webp
  public/img/posts/asyncapiXhacktoberfest.webp
Labels: Hacktoberfest, ready-to-merge

#1155 chore: add new tool categories - api and editor
  config/tools-manual.json
  scripts/tools/categorylist.js
Labels: ready-to-merge

#1161 chore: improve json schema for `.asyncapi-tool`
  scripts/tools/tools-schema.json
Labels: ready-to-merge

#1139 docs: new cli install fragment
  assets/docs/fragments/cli-installation.md
  components/MDX.js
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#1180 fix: wrong updation of DocsNavItem
  components/navigation/DocsNav.js
  components/navigation/DocsNavItem.js
Labels: ready-to-merge

#940 feat: added new /tools page
  components/buttons/Button.js
  components/icons/ArrowDown.js
  components/icons/Filter.js
  components/icons/Search.js
  components/navigation/communityItems.js
  components/tools/Filters.js
  components/tools/FiltersDropdown.js
  components/tools/Tags.js
  components/tools/ToolDashboard.js
  components/tools/ToolsCard.js
  components/tools/ToolsList.js
  config/all-tags.json
  config/tools-automated.json
  config/tools.json
  context/ToolFilterContext.js
  pages/tools/index.js
  public/img/illustrations/icons/CheckedIcon.svg
  public/img/illustrations/icons/FreeIcon.svg
  public/img/illustrations/icons/PaidIcon.svg
  public/img/illustrations/icons/UncheckedIcon.svg
  public/img/illustrations/icons/share.svg
  public/img/illustrations/not-found.webp
  public/img/logos/github-black.svg
  scripts/tools/categorylist.js
  scripts/tools/combine-tools.js
  scripts/tools/tags-color.js
  scripts/tools/tools-object.js
  scripts/tools/tools-schema.json
  tailwind.config.js
Labels: ready-to-merge

#1185 feat: add text when no events
  components/Calendar.js
Labels: ready-to-merge

#1138 fix(deps): downgrade react-syntax-highlighter version to fix code h…
  package-lock.json
  package.json
Labels: ready-to-merge

#1184 fix: change link for subscribe button
  pages/index.js
Labels: ready-to-merge
