Repository asyncapi/website, pull requests merged in 2022-04, with the labels that each got.

#644 feat: add new newsletter view
  components/NewsletterSubscribe.js
  components/layout/BlogLayout.js
  components/layout/DocsLayout.js
  components/layout/GenericLayout.js
  components/layout/GenericPostLayout.js
  components/layout/GenericWideLayout.js
  components/layout/JobsLayout.js
  pages/_app.js
  pages/blog/index.js
  pages/index.js
  pages/jobs/index.js
  pages/newsletter/index.js
Labels: ready-to-merge

#651 chore: exchanged yt video with link reference in /event-driven-archit…
  pages/docs/getting-started/event-driven-architectures.md
Labels: good first issue, 📑 docs, area/docs

#630 ci: add lighthouse ci for tracking website performance
  .github/workflows/lighthouse-ci.yml
  .github/workflows/lighthouserc.json
Labels: ready-to-merge

#650 docs: fix misspelling and add installation guide in streetlights tutorial
  pages/docs/tutorials/streetlights.md
Labels: good first issue, ready-to-merge, 📑 docs, 🐞 docs bug, area/docs

#637 chore: update og tag image
  components/Head.js
  pages/community/tsc.js
  pages/roadmap.js
  pages/tools/cli.js
  pages/tools/generator.js
  pages/tools/github-actions.js
  pages/tools/modelina.js
  pages/tools/parsers.js
  public/img/social/card.png
  public/img/social/cli-card.jpg
  public/img/social/generator-card.jpg
  public/img/social/generator.png
  public/img/social/github-actions.png
  public/img/social/githubactions-card.jpg
  public/img/social/modelina-card.jpg
  public/img/social/modelina.png
  public/img/social/parsers-card.jpg
  public/img/social/parsers.png
  public/img/social/roadmap.png
  public/img/social/tsc.png
  public/img/social/website-card.jpg
Labels: ready-to-merge

#678 chore: removed the emoji from streetlights tutorial
  pages/docs/tutorials/streetlights.md
Labels: ready-to-merge

#609 feat: docs feedback form created
  .env
  .gitpod.yml
  README.md
  components/Feedback.js
  components/Head.js
  components/buttons/GitHubIssue.js
  components/layout/DocsLayout.js
  netlify.toml
  netlify/functions/github_discussions.js
  package.json
  pages/blog/march-2021-at-asyncapi.md
  public/img/illustrations/icons/icon-check.svg
  public/img/illustrations/icons/icon-x.svg
  public/img/illustrations/icons/icon.svg
  public/img/logos/github-fill.svg
Labels: ready-to-merge

#687 fix: docs feedback
  components/Feedback.js
  components/buttons/GitHubIssue.js
  netlify/functions/github_discussions.js
Labels: ready-to-merge

#685 docs: change misspelling at the next and back button and fix 404 not found button result
  pages/docs/specifications/v2.2.0.md
  pages/docs/tutorials/streetlights-interactive.md
Labels: ready-to-merge

#700 fix: updated broken restream link
  components/SupportUs.js
Labels: ready-to-merge

#634 feat(blog): add release notes for 2.4 release
  pages/blog/release-notes-2.4.0.md
  public/img/posts/release-notes-2.4.0/cover.webp
Labels: autoupdate

#689 docs: removed the faulty release file and it's redirects
  pages/docs/specifications/v2.3.1-2022-04-release.1.md
  public/_redirects
Labels: 🐞 docs bug, area/docs

#656 feat(blog): add article about things that happened in asyncapi in Q1
  pages/blog/2021-summary.md
  pages/blog/2022Q1-summary.md
  pages/blog/asyncapi-and-apicurio-for-asynchronous-apis.md
  pages/blog/changes-coming-docs.md
  pages/blog/july-december-2021-at-asyncapi.md
  pages/blog/openforce-2022.md
  pages/blog/release-notes-2.3.0.md
  public/img/posts/2022Q1-summary/cover.webp
  public/img/posts/2022Q1-summary/meetings.webp
Labels: ready-to-merge

#720 docs: update next and prev button links due to spec updates
  pages/docs/specifications/v2.3.0.md
  pages/docs/specifications/v2.4.0.md
  pages/docs/tutorials/streetlights-interactive.md
Labels: good first issue, ready-to-merge, 🐞 docs bug, area/docs
