Repository asyncapi/website, pull requests merged in 2022-09, with the labels that each got.

#932 fix: nodejs-pr-testing workflow deleted
  .github/workflows/bump.yml
  .github/workflows/if-nodejs-pr-testing.yml
  .github/workflows/if-nodejs-release.yml
  .github/workflows/if-nodejs-version-bump.yml
Labels: ready-to-merge

#828 feat: press page
  components/Footer.js
  pages/about/index.md
Labels: ready-to-merge

#920 docs: fix OpenAPI comparison chart
  components/OpenAPIComparison.js
Labels: ready-to-merge

#882 feat: integrate mermaid in markdown code-blocks
  components/MDX.js
  package-lock.json
  package.json
  pages/_app.js
Labels: ready-to-merge

#807 docs: add server concepts doc
  pages/docs/concepts/server.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#956 docs: added new validator tools
  pages/docs/tools/index.md
Labels: 📑 docs, area/docs

#953 fix: update required versions of Node.js/npm in README.md
  README.md
Labels: ready-to-merge

#912 docs(blog): adds asyncapi with sqs blog post
  pages/blog/documenting-sqs-event-driven-apis-with-asyncapi.md
  public/img/avatars/mbosetti.webp
  public/img/posts/documenting-sqs-event-driven-apis-with-asyncapi/cover.webp
  public/img/posts/documenting-sqs-event-driven-apis-with-asyncapi/diagram.webp
  public/img/posts/documenting-sqs-event-driven-apis-with-asyncapi/visualizer.webp
Labels: ready-to-merge

#969 chore: remove wrong releases
  pages/docs/reference/specification/v2.4.0-2022-04-release.4.md
  pages/docs/reference/specification/v2.5.0-next-major-spec.1.md
Labels: ready-to-merge

#972 fix: roadmap bugs
  components/typography/Paragraph.js
  pages/roadmap.js
Labels: ready-to-merge

#963 docs: improve headers in server concept page
  pages/docs/concepts/server.md
Labels: ready-to-merge

#979 fix: specification doc items not rendered properly
  components/layout/DocsLayout.js
  scripts/build-post-list.js
Labels: ready-to-merge

#915 docs(blog): add article about event driven documentation
  pages/blog/event-driven-api-documentation-made-simple-clientside-rendering.md
  public/img/avatars/michalgornicki.webp
  public/img/posts/event-driven-API-documentation-made-simple/document-template.webp
  public/img/posts/event-driven-API-documentation-made-simple/documentation.webp
Labels: ready-to-merge

#959 chore(blog): add release notes for 2.5.0 release
  pages/blog/release-notes-2.5.0.md
  public/img/avatars/char0n.webp
  public/img/posts/release-notes-2.5.0/cover.webp
Labels: ready-to-merge
