Repository asyncapi/website, pull requests merged in 2023-12, with the labels that each got.

#1851 chore: release v3
  README.md
  components/Asyncapi3Comparison.js
  components/DemoAnimation.js
  components/GeneratorInstallation.js
  components/OpenAPIComparisonV3.js
  components/campaigns/AnnoucementHero.js
  components/campaigns/Banner.js
  components/data/buckets.js
  components/icons/Migration.js
  components/icons/Users.js
  components/navigation/NavBar.js
  components/navigation/learningItems.js
  cypress/test/Asyncapi3Comparison.cy.js
  pages/blog/release-notes-3.0.0.md
  pages/docs/community/_section.md
  pages/docs/concepts/application.md
  pages/docs/concepts/asyncapi-document/_section.md
  pages/docs/concepts/asyncapi-document/adding-bindings.md
  pages/docs/concepts/asyncapi-document/reply-info.md
  pages/docs/concepts/asyncapi-document/server-security.md
  pages/docs/concepts/asyncapi-document/structure.md
  pages/docs/concepts/asyncapi-document/tags.md
  pages/docs/guides/message-validation.md
  pages/docs/guides/validate.md
  pages/docs/migration/_section.md
  pages/docs/migration/index.md
  pages/docs/migration/migrating-to-v3.md
  pages/docs/reference/specification/v2.0.0.md
  pages/docs/reference/specification/v2.1.0.md
  pages/docs/reference/specification/v2.2.0.md
  pages/docs/reference/specification/v2.3.0.md
  pages/docs/reference/specification/v2.4.0.md
  pages/docs/reference/specification/v2.5.0.md
  pages/docs/reference/specification/v2.6.0.md
  pages/docs/reference/specification/v2.x.md
  pages/docs/reference/specification/v3.0.0.md
  pages/docs/tutorials/create-asyncapi-document.md
  pages/docs/tutorials/generate-code.md
  pages/docs/tutorials/getting-started/asyncapi-documents.md
  pages/docs/tutorials/getting-started/coming-from-openapi.md
  pages/docs/tutorials/getting-started/hello-world.md
  pages/docs/tutorials/getting-started/request-reply.md
  pages/docs/tutorials/getting-started/security.md
  pages/docs/tutorials/getting-started/servers.md
  pages/docs/tutorials/message-validation.md
  pages/docs/tutorials/streetlights-interactive.md
  pages/docs/tutorials/studio-document-validation.md
  pages/tools/cli.js
  pages/tools/github-actions.js
  pages/tools/parsers.js
  public/_redirects
  public/img/posts/release-notes-3.0.0/cover.webp
  public/robots.txt
Labels: do-not-merge, autoupdate

#2366 docs: fixed docs files with broken links
  pages/docs/tools/generator/hooks.md
Labels: 🐞 docs bug, area/docs

#2398 chore: fix wrong links for v2 migration guide
  pages/docs/migration/migrating-to-v3.md
Labels: ready-to-merge

#1657 fix: scroll-to-top button
  components/buttons/ScrollButton.js
  components/navigation/MobileNavMenu.js
  components/navigation/NavBar.js
Labels: ready-to-merge

#2405 fix: skip AnnouncementHero and Banner tests
  cypress/test/components/campaignTests/AnnouncementHero.cy.js
  cypress/test/components/campaignTests/Banner.cy.js
Labels: ready-to-merge

#1695 fix: add accordion to FAQ section
  components/MDX.js
  pages/about/index.md
Labels: ready-to-merge

#2415 docs: add Variables in URL
  pages/docs/concepts/asyncapi-document/variable-url.md
Labels: ready-to-merge

#1868 docs: introduce AsyncAPI document
  pages/docs/concepts/asyncapi-document/index.md
Labels: 📑 docs, area/docs, gsod

#2408 docs: add document for adding channel
  pages/docs/concepts/asyncapi-document/adding-channels.md
Labels: ready-to-merge

#2430 docs: fix title in adding-bindings.md
  pages/docs/concepts/asyncapi-document/adding-bindings.md
Labels: 🐞 docs bug, area/docs

#2409 docs: adding document for dynamic channel
  pages/docs/concepts/asyncapi-document/dynamic-channel-address.md
Labels: ready-to-merge

#2403 docs: adding content about adding operations
  pages/docs/concepts/asyncapi-document/adding-operations.md
Labels: ready-to-merge

#2410 docs: adding document for adding messages
  pages/docs/concepts/asyncapi-document/adding-messages.md
Labels: ready-to-merge

#2414 docs: add payload
  pages/docs/concepts/asyncapi-document/define-payload.md
Labels: ready-to-merge

#2417 docs: add reusable parts
  pages/docs/concepts/asyncapi-document/reusable-parts.md
Labels: ready-to-merge

#2411 docs: adding document for Messages and Operations reusability with Traits
  pages/docs/concepts/asyncapi-document/reusability-with-traits.md
Labels: ready-to-merge

#2407 docs: adding document for extending the AsyncAPI specification
  pages/docs/concepts/asyncapi-document/extending-specification.md
Labels: ready-to-merge

#2416 docs: add servers
  pages/docs/concepts/asyncapi-document/add-server.md
Labels: ready-to-merge

#2404 docs: added content for securing operations
  pages/docs/concepts/asyncapi-document/securing-operations.md
Labels: ready-to-merge

#2286 chore: store url update
  components/footer/FooterList.js
Labels: ready-to-merge

#2328 feat: create dropdown for docs sidebar
  components/icons/DocsArrow.js
  components/layout/DocsLayout.js
  components/navigation/DocsNav.js
  components/navigation/SubCategoryDocsNav.js
Labels: ready-to-merge

#2179 chore: add docker file
  .dockerignore
  Dockerfile
  README.md
Labels: ready-to-merge

#1673 feat: add table of contents in case study
  components/CaseTOC.js
  components/TOC.js
  components/helpers/useHeadingsObserver.js
  components/typography/Heading.js
  lib/staticHelpers.js
  pages/casestudies/[id].js
Labels: ready-to-merge

#2481 chore: update finance information and success stories
  components/FinancialSummary/AsyncAPISummary.js
  components/FinancialSummary/ContactUs.js
  components/FinancialSummary/OtherFormsComponent.js
  components/FinancialSummary/SponsorshipTiers.js
  components/FinancialSummary/SuccessStories.js
  components/icons/Twitter.js
  config/finance/2023/Expenses.yml
  config/finance/2023/ExpensesLink.yml
Labels: ready-to-merge

#2232 feat: add adopters section to case study page
  .gitignore
  config/adopters.yml
  cypress/test/components/CaseStudyCard.cy.js
  cypress/test/pages/casestudies/index.cy.js
  pages/casestudies/index.js
  scripts/adopters/index.js
  scripts/index.js
Labels: ready-to-merge

#2487 fix: regirects for version react on proper path
  public/_redirects
Labels: ready-to-merge
