Repository asyncapi/website, pull requests merged in 2023-06, with the labels that each got.

#1701 chore: may community update summary
  pages/blog/may-2023.md
  public/img/posts/2023-summary/blog-banner-may.webp
Labels: ready-to-merge

#1612 docs: fix minor typos and grammatical errors in create-asyncapi-document.md
  pages/docs/tutorials/create-asyncapi-document.md
Labels: ready-to-merge

#1752 docs(blog): may docs report
  pages/blog/2023-April-docs-report.md
  pages/blog/2023-may-docs-report.md
  public/img/posts/2023-may-docs-report.webp
Labels: ready-to-merge, 📑 docs, area/docs

#1758 docs: update generate-code.md to fix link to redirect to studio-document-validation
  pages/docs/tutorials/generate-code.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#1772 fix: broken link to message validation guide
  pages/docs/tutorials/message-validation.md
Labels: 🐞 docs bug, area/docs

#1757 docs(blog): a small update on the progress on 3.0
  pages/blog/the-new-era-approaches.md
  public/img/posts/the-new-era-approaches.webp
Labels: ready-to-merge

#1261 docs: add community docs bucket
  components/data/buckets.js
  components/docs/DocsCards.js
  components/icons/Users.js
  components/navigation/DocsNav.js
  components/navigation/LearningPanel.js
  components/navigation/learningItems.js
  components/tabs/Tabs.js
  pages/docs/community/_section.md
  pages/docs/community/index.md
Labels: enhancement, ready-to-merge, 📑 docs, area/docs

#1789 chore: fix syntax errors of the v3 document
  pages/blog/the-new-era-approaches.md
Labels: ready-to-merge

#1793 feat: adding unit tests for typography component
  components/typography/Paragraph.js
  components/typography/TextLink.js
  cypress/test/typography/Heading.cy.js
  cypress/test/typography/Paragraph.cy.js
  cypress/test/typography/TextLink.cy.js
Labels: ready-to-merge, gsoc

#1763 feat: adding unit tests for docsCards and feature folders
  components/docs/DocsCards.js
  components/features/FeatureList.js
  components/features/index.jsx
  cypress/test/docs/DocsCards.cy.js
  cypress/test/features/index.cy.js
Labels: ready-to-merge, gsoc

#1761 feat: adding unit tests for community folder
  components/community/Card.js
  components/community/Header.js
  components/community/Hero.js
  components/community/HomeCard.js
  cypress/test/community/Card.cy.js
  cypress/test/community/Header.cy.js
  cypress/test/community/Hero.cy.js
  cypress/test/community/HomeCard.cy.js
Labels: ready-to-merge, gsoc

#1802 feat: adding stylesheets to cypress components
  cypress/support/component.js
Labels: ready-to-merge

#1204 fix: sanitize code from the TOC
  components/TOC.js
Labels: ready-to-merge

#1739 chore: rm modelina files and folders
  components/editor/MonacoEditorWrapper.js
  components/modelina/CSharpGenerator.js
  components/modelina/GoGenerator.js
  components/modelina/JavaGenerator.js
  components/modelina/JavaScriptGenerator.js
  components/modelina/TypeScriptGenerator.js
  config/modelina-language-options.json
Labels: ready-to-merge

#1727 ci: set output has been updated to use GITHUB_OUTPUT #1726
  .github/workflows/lighthouse-ci.yml
  pages/blog/automated-releases.md
Labels: ready-to-merge

#1838 fix: reverted the mdx-js loader to "1.6.4"
  package-lock.json
  package.json
Labels: ready-to-merge

#1836 docs: add new bundler to tooling page
  config/tools-manual.json
Labels: ready-to-merge

#1678 chore: new fragment for contributor questions section
  assets/docs/fragments/how-to-contribute.md
Labels: ready-to-merge, 📑 docs, area/docs

#1806 chore: prepare for v3 release
  README.md
  pages/docs/concepts/application.md
  pages/docs/guides/message-validation.md
  pages/docs/guides/validate.md
  pages/docs/tutorials/create-asyncapi-document.md
  pages/docs/tutorials/getting-started/asyncapi-documents.md
  pages/docs/tutorials/getting-started/coming-from-openapi.md
  pages/docs/tutorials/getting-started/hello-world.md
  pages/docs/tutorials/getting-started/security.md
  pages/docs/tutorials/getting-started/servers.md
  pages/docs/tutorials/streetlights-interactive.md
  pages/docs/tutorials/studio-document-validation.md
  pages/tools/parsers.js
Labels: ready-to-merge

#659 chore(blog): add release notes for 3.0
  pages/blog/release-notes-3.0.0.md
Labels: ready-to-merge
