Repository asyncapi/website, pull requests merged in 2023-04, with the labels that each got.

#1459 fix: fixed the about page rendering
  components/layout/GenericPostLayout.js
  lib/api.js
Labels: ready-to-merge

#1431 docs: update links to the AsyncAPI Docs Board
  pages/docs/concepts/index.md
  pages/docs/guides/index.md
  pages/docs/reference/index.md
  pages/docs/tools/index.md
  pages/docs/tutorials/index.md
Labels: 📑 docs, area/docs

#1484 fix: make meetings sorting more accurate
  components/navigation/EventFilter.js
  components/navigation/EventPostItem.js
  lib/staticHelpers.js
  pages/community/events/index.js
  scripts/build-meetings.js
Labels: ready-to-merge

#1474 feat: added sessionize logo in supported us section
  components/SupportUs.js
  public/img/supportus/sessionize.webp
Labels: ready-to-merge

#1491 feat: updated meetings script maxTime to 30 days
  scripts/build-meetings.js
Labels: ready-to-merge

#1396 feat: added ScrollToTopButton
  components/buttons/ScrollButton.js
  pages/_app.js
  public/img/loaders/scroll.svg
  styles/globals.css
Labels: ready-to-merge

#1495 fix: update preview image path for community pages
  pages/community/ambassadors/index.js
  pages/community/events/index.js
  pages/community/index.js
  pages/community/newsroom.js
  pages/community/tsc.js
  public/img/social/community-ambasaadors.webp
  public/img/social/community-events.webp
  public/img/social/community-newsroom.webp
  public/img/social/community-tsc.webp
  public/img/social/community.webp
Labels: ready-to-merge

#1462 feat: 404 page design
  pages/404.js
  public/img/illustrations/illustration.webp
Labels: ready-to-merge

#1560 fix: update slack component's image url
  components/slack/index.js
Labels: ready-to-merge

#1527 chore: new docs blog post sharing Q1 Docs Report
  pages/blog/2023-Q1-docs-report.md
  public/img/posts/Q1-asyncapidocs-report.webp
Labels: area/docs, gsod

#1552 feat: fixed alignment of labels in casestudies section
  pages/casestudies/[id].js
Labels: ready-to-merge

#1548 feat: added ambassador video Issue #1546
  pages/community/ambassadors/index.js
Labels: ready-to-merge

#1497 feat: persist filters as URL query params on Tools page
  components/tools/Carddata.js
  components/tools/Filters.js
  components/tools/ToolDashboard.js
  context/ToolFilterContext.js
  pages/tools/index.js
Labels: ready-to-merge

#1506 feat: open TSC members social links in a new tab
  pages/community/tsc.js
Labels: ready-to-merge

#1392 feat: aligned contribution guide button on dasboard
  components/dashboard/Header.js
  tailwind.config.js
Labels: ready-to-merge

#1583 fix: social links of ambassadors are not redirecting to correct link #1581
  pages/community/ambassadors/index.js
Labels: ready-to-merge

#1464 fix: improve docs pages accessibility
  components/Feedback.js
  components/Footer.js
  components/buttons/GitHubIssue.js
  components/navigation/MobileNavMenu.js
  components/navigation/NavBar.js
Labels: ready-to-merge
