Repository asyncapi/website, pull requests merged in 2023-07, with the labels that each got.

#1722 refactor: update maintainers list, introduce isTscMember key, and remove tsc_member.json file
  config/MAINTAINERS.json
  config/TSC_MEMBERS.json
  package.json
  pages/community/tsc.js
  scripts/index.js
Labels: ready-to-merge

#1894 style: dynamic logo colors for brands
  components/logos/Adidas.js
  components/logos/Axway.js
  components/logos/SAP.js
  components/logos/Salesforce.js
  components/logos/Slack.js
  pages/index.js
Labels: ready-to-merge

#1880 docs(blog): june-2023 community update
  pages/blog/april-2023.md
  pages/blog/june-2023.md
  pages/blog/march-2023.md
  pages/blog/may-2023.md
  public/img/posts/2023-summary/blog-banner-june.webp
Labels: ready-to-merge

#1791 feat: adding unit tests for roadmap component
  components/roadmap/RoadmapColumn.js
  components/roadmap/RoadmapItem.js
  components/roadmap/RoadmapList.js
  cypress/test/Roadmap/RoadmapColumn.cy.js
  cypress/test/Roadmap/RoadmapItem.cy.js
  cypress/test/Roadmap/RoadmapList.cy.js
Labels: ready-to-merge, gsoc

#1804 feat: adding unit tests for sponsors component
  components/GoldSponsors.js
  components/MDX.js
  components/SilverSponsors.js
  components/Sponsors.js
  components/sponsors/GoldSponsors.js
  components/sponsors/GoldSponsorsList.js
  components/sponsors/SilverSponsors.js
  components/sponsors/SilverSponsorsList.js
  components/sponsors/Sponsors.js
  components/sponsors/SponsorsList.js
  cypress/test/sponsors/GoldSponsors.cy.js
  cypress/test/sponsors/SilverSponsors.cy.js
  cypress/test/sponsors/Sponsors.cy.js
  pages/index.js
Labels: ready-to-merge, gsoc

#1811 feat: adding unit tests for calendar modal and caption component
  components/Calendar.js
  components/Caption.js
  components/Modal.js
  cypress/test/Calendar.cy.js
  cypress/test/Caption.cy.js
  cypress/test/Modal.cy.js
Labels: ready-to-merge, gsoc

#1809 feat: adding unit tests for footer component
  components/Footer.js
  components/footer/Footer.js
  components/footer/FooterList.js
  components/layout/GenericLayout.js
  components/layout/GenericPostLayout.js
  components/layout/GenericWideLayout.js
  components/layout/JobsLayout.js
  cypress/test/footer/Footer.cy.js
  pages/_app.js
  pages/blog/index.js
  pages/jobs/index.js
Labels: ready-to-merge, gsoc

#1775 feat: adding unit tests for form and slack folders
  components/form/Select.js
  components/slack/Message.js
  components/slack/index.js
  cypress/test/form/Select.cy.js
  cypress/test/slack/Message.cy.js
  cypress/test/slack/index.cy.js
Labels: ready-to-merge, gsoc

#1735 feat: adding unit tests for dashboard folder
  components/buttons/GithubButton.js
  components/buttons/SlackButton.js
  components/dashboard/GoodFirstIssues.js
  components/dashboard/GoodFirstIssuesTip.js
  components/dashboard/Header.js
  components/dashboard/table/Filters.js
  components/dashboard/table/Pagination.js
  components/dashboard/table/Row.js
  cypress/test/dashboard/GoodFirstIssues.cy.js
  cypress/test/dashboard/GoodFirstIssuesTip.cy.js
  cypress/test/dashboard/Header.cy.js
  cypress/test/dashboard/table/Filters.cy.js
  cypress/test/dashboard/table/Row.cy.js
  cypress/test/dashboard/table/Table.cy.js
Labels: ready-to-merge, gsoc

#1908 chore(blog): docs June report
  pages/blog/2023-june-docs-report.md
  pages/blog/2023-may-docs-report.md
  public/img/posts/2023-june-docs-report.webp
Labels: ready-to-merge, 📑 docs, area/docs

#1813 feat: adding unit tests for support-us,Testimonial and JobSummary component
  components/JobSummary.js
  components/SupportUs.js
  components/SupportUs/SupportItemsList.js
  components/SupportUs/SupportUs.js
  components/Testimonial.js
  cypress/test/JobSummary.cy.js
  cypress/test/SupportUs.cy.js
  cypress/test/Testimonial.cy.js
  pages/index.js
Labels: ready-to-merge, gsoc

#1921 fix: improved styling for annoucement hero
  components/campaigns/AnnoucementHero.js
Labels: ready-to-merge

#1818 feat: adding unit tests for button component
  components/buttons/Button.js
  components/buttons/ChapterSuggestion.js
  components/buttons/DocsButton.js
  components/buttons/GitHubIssue.js
  components/buttons/ICSFileButton.js
  cypress/test/buttons/ApplyJob.cy.js
  cypress/test/buttons/Buttons.cy.js
  cypress/test/buttons/ChapterSuggestion.cy.js
  cypress/test/buttons/DocsButton.cy.js
  cypress/test/buttons/GithubButton.cy.js
  cypress/test/buttons/GithubIssue.cy.js
  cypress/test/buttons/GoogleCalendarButton.cy.js
  cypress/test/buttons/ICSFileButton.cy.js
  cypress/test/buttons/OpenInPlaygroundButton.cy.js
  cypress/test/buttons/OpenInStudioButton.cy.js
  cypress/test/buttons/SlackButton.cy.js
  cypress/test/buttons/SubscribeButton.cy.js
  cypress/test/buttons/YoutubeButton.cy.js
Labels: ready-to-merge, gsoc

#1936 feat: mark some items as done in the roadmap
  pages/roadmap.js
Labels: ready-to-merge

#1941 feat: add example of version of schema in adeo.yml file
  config/casestudies/adeo.yml
Labels: ready-to-merge

#1949 fix: meeting link issue fixed
  public/_redirects
Labels: ready-to-merge

#1914 feat: adding unit tests for layout component
  components/AlgoliaSearch.js
  components/Head.js
  components/layout/BlogLayout.js
  components/layout/Column.js
  components/layout/Container.js
  components/layout/DocsLayout.js
  components/layout/GenericLayout.js
  components/layout/GenericPostLayout.js
  components/layout/GenericWideLayout.js
  components/layout/JobsLayout.js
  components/layout/Layout.js
  components/layout/Row.js
  cypress/fixtures/blogpost.json
  cypress/fixtures/docspost.json
  cypress/fixtures/jobpost.json
  cypress/test/layout/BlogLayout.cy.js
  cypress/test/layout/Column.cy.js
  cypress/test/layout/Container.cy.js
  cypress/test/layout/DocsLayout.cy.js
  cypress/test/layout/GenericLayout.cy.js
  cypress/test/layout/GenericPostLayout.cy.js
  cypress/test/layout/JobsLayout.cy.js
  cypress/test/layout/Layout.cy.js
  cypress/test/layout/Row.cy.js
  cypress/utils/router.js
Labels: ready-to-merge, gsoc

#1827 feat: adding unit tests for InlineHelp ,MacWindow , Newsletter , Profile ,Remember and Warning components
  components/InlineHelp.js
  components/MacWindow.js
  components/NewsletterSubscribe.js
  components/Profile.js
  components/Remember.js
  components/Warning.js
  cypress/test/InlineHelp.cy.js
  cypress/test/MacWindow.cy.js
  cypress/test/NewsletterSubscribe.cy.js
  cypress/test/Profile.cy.js
  cypress/test/Remember.cy.js
  cypress/test/Warning.cy.js
Labels: ready-to-merge, gsoc

#1724 feat: add unit tests for campaigns folder
  components/campaigns/AnnoucementHero.js
  components/campaigns/AnnouncementRamainingDays.js
  components/campaigns/Banner.js
  cypress/test/ComponentName.cy.js
  cypress/test/campaignTests/AnnouncementHero.cy.js
  cypress/test/campaignTests/AnnouncementRemainingDays.cy.js
  cypress/test/campaignTests/Banner.cy.js
Labels: ready-to-merge, gsoc

#1918 fix: resolve CSS issues in the roadmap item modal
  components/Modal.js
Labels: ready-to-merge

#1916 feat: add unit tests for AlgoliaSearch,GeneratorInstallation and OpenAPIComparison component
  components/OpenAPIComparison.js
  cypress/test/AlgoliaSearch.cy.js
  cypress/test/GeneratorInstallation.cy.js
  cypress/test/OpenAPIComparison.cy.js
Labels: ready-to-merge, gsoc

#1891 feat: adding unit tests for newsroom component
  components/newsroom/FeaturedBlogPost.js
  components/newsroom/Newsroom.js
  components/newsroom/NewsroomArticle.js
  components/newsroom/NewsroomBlogPosts.js
  components/newsroom/NewsroomSection.js
  components/newsroom/NewsroomYoutube.js
  components/newsroom/YouTubeCard.js
  cypress/test/mockData/blogmockData.js
  cypress/test/newsroom/FeaturedBlogItem.cy.js
  cypress/test/newsroom/Newsroom.cy.js
  cypress/test/newsroom/NewsroomArticle.cy.js
  cypress/test/newsroom/NewsroomBlogPost.cy.js
  cypress/test/newsroom/NewsroomSection.cy.js
  cypress/test/newsroom/NewsroomYoutube.cy.js
  cypress/test/newsroom/YoutubeCard.cy.js
  cypress/test/newsroom/swiper.cy.js
Labels: ready-to-merge, gsoc

#1964 chore: add jasyncapicmp to the file tools-manual.json
  components/tools/ToolsCard.js
  config/tools-manual.json
  config/tools.json
Labels: ready-to-merge

#1961 feat: add tests for lib folder
  cypress/test/lib/api.cy.js
  cypress/test/lib/staticHelpers.cy.js
Labels: ready-to-merge

#1973 chore: remove obsolete monaco dependency
  package-lock.json
  package.json
Labels: ready-to-merge

#1831 feat: add unit tests for AuthorAvatars , TOC , Hero , Meeting and DemoAnimation and Figure components
  components/AlgoliaSearch.js
  components/AuthorAvatars.js
  components/Feedback.js
  components/Figure.js
  components/Hero.js
  components/Meeting.js
  components/TOC.js
  cypress/test/AuthorAvatars.cy.js
  cypress/test/DemoAnimation.cy.js
  cypress/test/Feedback.cy.js
  cypress/test/Figure.cy.js
  cypress/test/Hero.cy.js
  cypress/test/Meeting.cy.js
  cypress/test/TOC.cy.js
Labels: ready-to-merge, gsoc

#1627 fix: updated tools workflow
  config/all-tags.json
  config/tools-automated.json
  config/tools.json
  scripts/build-tools.js
  scripts/tools/extract-tools-github.js
  scripts/tools/tags-color.js
  scripts/tools/tools-object.js
Labels: ready-to-merge

#1955 fix: made the links width 100%
  components/navigation/DocsNavItem.js
Labels: ready-to-merge

#1885 feat: adding unit tests for editor component
  components/editor/CodeBlock.js
  cypress/test/editor/CodeBlock.cy.js
Labels: ready-to-merge, gsoc

#1988 feat: add unit tests for newsroom-videos scripts
  cypress/test/mockData/mockData.json
  cypress/test/scripts/build-newsroom-videos.cy.js
  scripts/build-newsroom-videos.js
Labels: ready-to-merge, gsoc
