Repository asyncapi/website, pull requests merged in 2023-01, with the labels that each got.

#1207 fix: space in TOC section
  components/TOC.js
Labels: ready-to-merge

#1211 docs: update tooling url from corunet domain to sngular
  pages/docs/tools/index.md
Labels: ready-to-merge, 📑 docs, area/docs

#1169 chore(blog): conference 2022 blog post
  pages/blog/conference-2022.md
  public/img/posts/conference-2022.webp
  public/img/sponsors/ably.png
Labels: ready-to-merge

#1191 feat: manual tools added to the Tools Dashboard
  components/navigation/communityItems.js
  components/tools/Filters.js
  components/tools/ToolDashboard.js
  components/tools/ToolsCard.js
  components/tools/ToolsList.js
  config/all-tags.json
  config/tools-automated.json
  config/tools-manual.json
  config/tools.json
  package-lock.json
  package.json
  public/img/illustrations/icons/docs-icon.svg
  scripts/build-tools.js
  scripts/tools/categorylist.js
  scripts/tools/combine-tools.js
  scripts/tools/tags-color.js
  scripts/tools/tools-object.js
  scripts/tools/tools-schema.json
Labels: ready-to-merge

#1134 chore(blog): article proposal based on basic concepts about APIs
  components/Figure.js
  pages/blog/a_straight_guide_to_apis_and_architecture_concepts.md
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/cover.webp
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/guide-pic._01.webp
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/guide-pic._02.webp
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/guide-pic._03.webp
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/guide-pic._04.webp
  public/img/posts/a_straight_guide_to_apis_and_architecture_concepts/guide-pic._05.webp
Labels: ready-to-merge

#1226 fix: tools workflow file changed
  .github/workflows/regenerate-tools.yml
  config/all-tags.json
  config/tools-automated.json
  config/tools.json
Labels: ready-to-merge

#1188 fix: automated DocsButton
  components/MDX.js
  components/buttons/DocsButton.js
  components/layout/DocsLayout.js
  components/layout/Layout.js
  lib/api.js
  pages/docs/concepts/application.md
  pages/docs/concepts/channel.md
  pages/docs/concepts/consumer.md
  pages/docs/concepts/index.md
  pages/docs/concepts/message.md
  pages/docs/concepts/producer.md
  pages/docs/concepts/protocol.md
  pages/docs/concepts/server.md
  pages/docs/guides/index.md
  pages/docs/reference/index.md
  pages/docs/tools/index.md
  pages/docs/tutorials/getting-started/asyncapi-documents.md
  pages/docs/tutorials/getting-started/coming-from-openapi.md
  pages/docs/tutorials/getting-started/event-driven-architectures.md
  pages/docs/tutorials/getting-started/hello-world.md
  pages/docs/tutorials/getting-started/index.md
  pages/docs/tutorials/getting-started/security.md
  pages/docs/tutorials/getting-started/servers.md
  pages/docs/tutorials/index.md
  pages/docs/tutorials/streetlights-interactive.md
  pages/docs/tutorials/streetlights.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#1232 fix: sorting order in tools dashboard
  scripts/tools/combine-tools.js
Labels: ready-to-merge

#1123 feat: ambassador program page
  config/tools-automated.json
  config/tools.json
  pages/community/ambassadors/[id].js
  pages/community/ambassadors/index.js
  public/img/homepage/ambassador-cover.svg
  public/img/homepage/gathering.jpg
  public/img/homepage/mapbase.png
  public/img/illustrations/advisor.svg
  public/img/illustrations/blog.svg
  public/img/illustrations/codes.svg
  public/img/illustrations/learning-app.svg
  public/img/illustrations/live.svg
  public/img/illustrations/meeting.jpg
  public/img/illustrations/meeting.svg
  public/img/illustrations/speaking.svg
  public/img/illustrations/video-creation.svg
  tailwind.config.js
Labels: enhancement, ready-to-merge

#1208 chore: unlink roadmap from shape-up-process repo
  .gitignore
  components/Modal.js
  components/roadmap/RoadmapItem.js
  pages/roadmap.js
  scripts/build-roadmap.js
  scripts/index.js
Labels: ready-to-merge
