Repository asyncapi/website, pull requests merged in 2023-11, with the labels that each got.

#2008 docs: add v3 migration guide
  components/Asyncapi3Comparison.js
  components/data/buckets.js
  components/icons/Migration.js
  components/icons/Users.js
  components/navigation/learningItems.js
  cypress/test/Asyncapi3Comparison.cy.js
  pages/docs/community/_section.md
  pages/docs/migration/_section.md
  pages/docs/migration/index.md
  pages/docs/migration/migrating-to-v3.md
Labels: ready-to-merge

#2185 chore(blog): add the summary for september & october
  pages/blog/august-2023.md
  pages/blog/september-2023.md
  public/img/posts/2023-summary/blog-banner-october.webp
  public/img/posts/2023-summary/blog-banner-september.webp
Labels: ready-to-merge

#2288 feat: add global eslint plugin
  .eslintrc.js
  package-lock.json
  package.json
Labels: ready-to-merge

#2281 feat: cleanup reference docs for 3.0
  pages/docs/reference/specification/v2.0.0.md
  pages/docs/reference/specification/v2.1.0.md
  pages/docs/reference/specification/v2.2.0.md
  pages/docs/reference/specification/v2.3.0.md
  pages/docs/reference/specification/v2.4.0.md
  pages/docs/reference/specification/v2.5.0.md
  pages/docs/reference/specification/v2.6.0.md
  pages/docs/reference/specification/v2.x.md
  pages/docs/reference/specification/v3.0.0.md
  public/_redirects
Labels: ready-to-merge

#2218 feat: add banners for cfp for Bengaluru and Paris
  components/campaigns/AnnoucementHero.js
  cypress/test/components/campaignTests/AnnouncementHero.cy.js
Labels: ready-to-merge

#2306 fix: remaining days and mobile view issue of conference banners
  components/campaigns/AnnoucementHero.js
  components/campaigns/AnnouncementRemainingDays.js
  cypress/test/components/campaignTests/AnnouncementRemainingDays.cy.js
Labels: ready-to-merge

#2299 chore: update instructions for some tools promotion usage
  components/GeneratorInstallation.js
  pages/tools/cli.js
  pages/tools/github-actions.js
Labels: ready-to-merge

#2275 docs: re-add `Servers tutorial` and change code snippet
  pages/docs/tutorials/getting-started/servers.md
Labels: ready-to-merge

#2282 docs: re-add `message validation guide` and change code snippet
  pages/docs/guides/message-validation.md
Labels: ready-to-merge

#2303 docs: re-add `Validate AsyncAPI documents`
  pages/docs/guides/validate.md
Labels: ready-to-merge

#2276 docs: re-add `studio document validation` and change code snippet
  pages/docs/tutorials/studio-document-validation.md
Labels: ready-to-merge

#2304 docs: re-add `Create AsyncAPI document`
  pages/docs/tutorials/create-asyncapi-document.md
Labels: ready-to-merge

#2274 docs: re-add `AsyncAPI Documents` and change code snippet
  pages/docs/tutorials/getting-started/asyncapi-documents.md
Labels: ready-to-merge

#2004 docs: hello world tutorial for AsyncApi v3
  pages/docs/tutorials/getting-started/hello-world.md
Labels: ready-to-merge

#2307 docs: re-add `Coming from OpenAPI`
  components/Asyncapi3Comparison.js
  components/OpenAPIComparisonV3.js
  pages/docs/tutorials/getting-started/coming-from-openapi.md
Labels: ready-to-merge

#2300 test: fixing flakiness of scripts/build-newsroom-videos.cy.js
  cypress/test/scripts/build-newsroom-videos.cy.js
Labels: ready-to-merge

#2228 docs: adding `reply` info in a AsyncAPI document
  pages/docs/concepts/asyncapi-document/_section.md
  pages/docs/concepts/asyncapi-document/reply-info.md
Labels: ready-to-merge

#2235 docs: tutorial introducing request/reply
  pages/docs/tutorials/getting-started/request-reply.md
Labels: ready-to-merge

#1922 docs: structure of a AsyncAPI document
  pages/docs/concepts/asyncapi-document/structure.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#2042 docs: add document for adding binding page
  pages/docs/concepts/asyncapi-document/adding-bindings.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#2231 docs: adding document for servers' security
  pages/docs/concepts/asyncapi-document/server-security.md
Labels: ready-to-merge

#2325 docs: fix/commit tw changes due to early merge of PR2231
  pages/docs/concepts/asyncapi-document/server-security.md
Labels: 📑 docs, area/docs, gsod

#1957 docs: tags in a AsyncAPI document
  pages/docs/concepts/asyncapi-document/tags.md
Labels: ready-to-merge, 📑 docs, area/docs, gsod

#2343 feat: update banner link
  components/campaigns/AnnoucementHero.js
Labels: ready-to-merge

#2344 fix: update slack link
  public/_redirects
Labels: ready-to-merge

#2316 chore: add finishing details to the v3 release blog
  pages/blog/release-notes-3.0.0.md
Labels: ready-to-merge

#2356 fix: conf banner alignment fix
  components/campaigns/AnnoucementHero.js
  cypress/test/pages/community/dashboard.cy.js
Labels: ready-to-merge

#2013 chore: acknowledgement for v3
  pages/blog/release-notes-3.0.0.md
Labels: ready-to-merge

#2293 chore: add parameter section in migration
  components/Asyncapi3Comparison.js
  pages/docs/migration/migrating-to-v3.md
Labels: ready-to-merge

#2317 docs: migrate code generation and message validation tutorials to use Glee
  pages/docs/tutorials/generate-code.md
  pages/docs/tutorials/message-validation.md
Labels: ready-to-merge, 📑 docs
