Repository asyncapi/website, pull requests merged in 2023-03, with the labels that each got.

#1326 refactor: remove blank space
  components/dashboard/table/Pagination.js
Labels: ready-to-merge

#1377 docs: fix tutorials getting started weight + edits
  pages/docs/tutorials/getting-started/event-driven-architectures.md
  pages/docs/tutorials/getting-started/index.md
  public/_redirects
Labels: ready-to-merge

#1380 fix: minor enhancements
  components/icons/Ambassador.js
  components/icons/Overview.js
  components/navigation/MobileNavMenu.js
  components/navigation/NavBar.js
  components/navigation/communityItems.js
  pages/community/meetings.js
Labels: ready-to-merge

#1196 feat: blog post on SIO-AsyncAPI
  pages/blog/socketio-automatic-docs.md
  public/img/avatars/dalerrahimov.webp
  public/img/posts/socketio-automatic-docs/cover.webp
  public/img/posts/socketio-automatic-docs/sio-asycnapi-pic1.webp
  public/img/posts/socketio-automatic-docs/sio-asycnapi-pic2.webp
Labels: ready-to-merge

#1390 feat: improved drop down list
  components/dashboard/GoodFirstIssues.js
  components/dashboard/table/Filters.js
Labels: ready-to-merge

#1293 docs: add local setup documentation for website readme
  README.md
Labels: ready-to-merge

#1321 docs: update versions from 2.5.0 to 2.6.0 in docs pages
  pages/docs/tools/generator/parser.md
  pages/docs/tutorials/getting-started/hello-world.md
Labels: ready-to-merge

#1395 feat: improved hot topics section of dashboard
  components/dashboard/table/Row.js
  pages/community/dashboard.js
Labels: ready-to-merge

#1330 feat: add jump to category dropdown in tools dashboard
  components/tools/CategoryDropdown.js
  components/tools/ToolDashboard.js
  components/tools/ToolsList.js
Labels: ready-to-merge

#1401 fix: codeblock and backticks styling
  components/editor/CodeBlock.js
Labels: ready-to-merge

#1413 fix: deleted .env file and updated .gitignore
  .env
  .gitignore
  components/Head.js
Labels: ready-to-merge

#1379 chore: post about the ambassador program
  pages/blog/asyncapi-ambassador-program.md
  public/img/posts/ambassador-program/cover.webp
Labels: ready-to-merge

#1387 fix: sponsor and supporters images/logos fix in low screens
  components/GoldSponsors.js
  components/SilverSponsors.js
  components/Sponsors.js
  components/SupportUs.js
Labels: ready-to-merge

#1055 docs: add interactive comparison w/ openapi
  components/OpenAPIComparison.js
Labels: enhancement, ready-to-merge, 📑 docs, area/docs

#1337 fix: added functionality to skip-to-content
  components/dashboard/Header.js
  components/layout/DocsLayout.js
  components/layout/GenericLayout.js
  components/navigation/NavBar.js
  pages/blog/index.js
  pages/jobs/index.js
  public/img/social/blog.webp
  public/img/social/job.webp
Labels: ready-to-merge

#1194 feat: add discussion saviour bot as as lambda function
  .gitignore
  netlify/functions/save-discussion/Reposity.ts
  netlify/functions/save-discussion/Slack.ts
  netlify/functions/save-discussion/helpers.ts
  netlify/functions/save-discussion/index.d.ts
  netlify/functions/save-discussion/index.ts
  package-lock.json
  package.json
Labels: ready-to-merge

#1444 docs: remove check_api from tools-manual.json
  config/tools-manual.json
Labels: ready-to-merge

#1451 fix: add valid social card for case studies
  pages/casestudies/index.js
  public/img/social/case-studies.webp
Labels: ready-to-merge

#1288 feat: new blog on AsyncAPI and TriggerMesh
  pages/blog/asyncapi-say-hi-to-triggermesh.md
  public/img/avatars/jmichaux.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/blog-graphic-asyncapi-triggermesh.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/full-schema.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/gcp-publish.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/poller-event.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/triggermesh-concepts.webp
  public/img/posts/asyncapi-say-hi-to-triggermesh/watch-new-order.webp
Labels: autoupdate

#1449 fix: event page update
  components/navigation/communityItems.js
  pages/community/events/index.js
  pages/community/index.js
Labels: ready-to-merge

#1472 chore: remove fmvilas as code owner
  CODEOWNERS
Labels: ready-to-merge

#1456 fix: toc items highlighting issue
  components/TOC.js
Labels: ready-to-merge

#1423 fix: fixed Clear Filter Bug
  components/tools/Filters.js
Labels: ready-to-merge

#1285 feat: add the preloader for tools section
  components/tools/ToolDashboard.js
  package-lock.json
  pages/tools/index.js
  public/img/loaders/loader.png
Labels: ready-to-merge
