Repository asyncapi/website, pull requests merged in 2023-08, with the labels that each got.

#2024 feat: disable Netlify caching for schemas serving + rely in GH caching
  netlify.toml
  netlify/edge-functions/serve-definitions.ts
Labels: ready-to-merge

#2050 fix: newsroom script workflow
  scripts/build-newsroom-videos.js
Labels: ready-to-merge

#1805 chore(blog): adding 3 New Articles as Blog Posts
  pages/blog/api-first-with-asyncapi.md
  pages/blog/jhipster-jdl-to-asyncapi.md
  pages/blog/zenwave-asyncapi-code-generator.md
  public/img/avatars/ivangsa.webp
  public/img/posts/zenwave/ZenWave360-AsyncAPI-SpringCloudStreams.png
  public/img/posts/zenwave/api-first-with-asyncapi-banner.png
  public/img/posts/zenwave/client-server-vs-broker-eda.excalidraw.svg
  public/img/posts/zenwave/jhipster-to-asyncapi-banner.png
  public/img/posts/zenwave/openapi-asyncapi.png
  public/img/posts/zenwave/spring-cloud-streams3-generated.png
Labels: ready-to-merge

#2045 feat: add unit tests for docs scripts
  cypress/fixtures/MockData-scripts.js
  cypress/test/scripts/build-docs.cy.js
  scripts/build-docs.js
Labels: ready-to-merge, gsoc

#2040 feat: add homepage translations for asyncapi website
  .gitignore
  components/Calendar.js
  components/Hero.js
  components/NewsletterSubscribe.js
  components/buttons/GoogleCalendarButton.js
  components/buttons/ICSFileButton.js
  components/buttons/SubscribeButton.js
  components/features/index.jsx
  components/newsroom/NewsroomSection.js
  cypress/test/Hero.cy.js
  cypress/test/buttons/GoogleCalendarButton.cy.js
  cypress/test/buttons/ICSFileButton.cy.js
  cypress/test/buttons/SubscribeButton.cy.js
  cypress/test/newsroom/NewsroomSection.cy.js
  locales/de/common.json
  locales/de/landing-page.json
  locales/en/common.json
  locales/en/landing-page.json
  next-i18next-static-site.config.js
  pages/[lang]/index.js
Labels: ready-to-merge

#2064 feat: add unit tests for case study card , check render of tools pages & newsletter
  components/CaseStudyCard.js
  cypress/test/CaseStudyCard.cy.js
  cypress/test/pages/casestudies/index.cy.js
  cypress/test/pages/newsletter/index.cy.js
  cypress/test/pages/tools/cli.cy.js
  cypress/test/pages/tools/generator.cy.js
  cypress/test/pages/tools/github-actions.cy.js
  cypress/test/pages/tools/index.cy.js
  cypress/test/pages/tools/modelina.cy.js
  cypress/test/pages/tools/parsers.cy.js
  pages/casestudies/index.js
  pages/tools/index.js
Labels: ready-to-merge, gsoc

#2047 feat: add unit tests for helpers and also fixes for existing tests
  components/campaigns/AnnoucementHero.js
  components/helpers/applyFilter.js
  cypress/test/Modal.cy.js
  cypress/test/campaignTests/AnnouncementHero.cy.js
  cypress/test/helpers/applyFilter.cy.js
  cypress/test/helpers/is-mobile.cy.js
Labels: ready-to-merge, gsoc

#1428 style: added badges and links in readme
  README.md
Labels: ready-to-merge

#2074 feat: add features list translations
  components/features/FeatureList.js
  components/features/index.jsx
  cypress/test/features/index.cy.js
  locales/de/landing-page.json
  locales/en/landing-page.json
Labels: ready-to-merge

#2069 feat: add unit tests for navigation component
  components/navigation/BlogPostItem.js
  components/navigation/DocsMobileMenu.js
  components/navigation/DocsNav.js
  components/navigation/EventPostItem.js
  components/navigation/FlyoutMenu.js
  components/navigation/MenuBlocks.js
  components/navigation/MobileNavMenu.js
  components/navigation/NavBar.js
  components/navigation/NavItem.js
  components/navigation/NavMenu.js
  components/navigation/StickyNavbar.js
  components/navigation/TutorialList.js
  cypress/fixtures/navigation-mock.js
  cypress/test/navigation/BlogPostItem.cy.js
  cypress/test/navigation/DocsNav.cy.js
  cypress/test/navigation/EventFilter.cy.js
  cypress/test/navigation/EventPostItem.cy.js
  cypress/test/navigation/FlyoutMenu.cy.js
  cypress/test/navigation/JobPostItem.cy.js
  cypress/test/navigation/MenuBlocks.cy.js
  cypress/test/navigation/MobileNavMenu.cy.js
  cypress/test/navigation/NavBar.cy.js
  cypress/test/navigation/NavItem.cy.js
  cypress/test/navigation/NavMenu.cy.js
  cypress/test/navigation/StickyNavbar.cy.js
Labels: ready-to-merge, gsoc

#2077 chore(blog): july docs report
  pages/blog/2023-july-docs-report.md
  pages/blog/2023-june-docs-report.md
  public/img/posts/2023-july-docs-report.webp
Labels: ready-to-merge, 📑 docs, area/docs, autoupdate

#1887 feat: adding unit tests for tools component
  components/tools/Carddata.js
  components/tools/CategoryDropdown.js
  components/tools/Filters.js
  components/tools/FiltersDisplay.js
  components/tools/FiltersDropdown.js
  components/tools/Tags.js
  components/tools/ToolDashboard.js
  components/tools/ToolsCard.js
  components/tools/ToolsList.js
  context/ToolFilterContext.js
  cypress/test/newsroom/FeaturedBlogItem.cy.js
  cypress/test/tools/Carddata.cy.js
  cypress/test/tools/CategoryDropdown.cy.js
  cypress/test/tools/Filters.cy.js
  cypress/test/tools/FiltersDisplay.cy.js
  cypress/test/tools/FiltersDropdown.cy.js
  cypress/test/tools/Tags.cy.js
  cypress/test/tools/ToolsCard.cy.js
  cypress/test/tools/ToolsDashboard.cy.js
  cypress/test/tools/ToolsList.cy.js
  cypress/utils/mockData/blogmockData.js
  cypress/utils/mockData/mockData.json
  cypress/utils/mockData/toolsmockData.js
  cypress/utils/router.js
Labels: ready-to-merge, gsoc

#2086 feat: add UI tests workflow
  .github/workflows/cypress-tests.yml
  cypress.config.js
  cypress/test/editor/CodeBlock.cy.js
  package.json
Labels: ready-to-merge, gsoc

#2106 feat: add AACoT London banner
  components/campaigns/AnnoucementHero.js
  cypress/test/campaignTests/AnnouncementHero.cy.js
Labels: ready-to-merge
