Repository asyncapi/website, pull requests merged in 2023-05, with the labels that each got.

#1621 fix: remove nested anchor tag inside button tag
  components/icons/NavItemDropdown.js
  components/navigation/NavItem.js
Labels: ready-to-merge

#1610 chore: make lighthouse check more radical
  .github/workflows/lighthouse-ci.yml
  .github/workflows/lighthouserc.json
Labels: ready-to-merge

#1617 docs: adeo case study links
  config/casestudies/adeo.yml
  public/resources/casestudies/adeo/asyncapi.yaml
Labels: ready-to-merge

#1628 fix: fixed the spacing between Navbar and Heading in Newsroom page
  components/newsroom/Newsroom.js
Labels: ready-to-merge

#1632 chore: new April docs report blog post
  pages/blog/2023-April-docs-report.md
  public/img/posts/2023-april-docs-report.webp
Labels: ready-to-merge, gsod

#1562 fix: use background functions instead of normal netlify functions
  netlify/functions/save-discussion-background/Reposity.ts
  netlify/functions/save-discussion-background/Slack.ts
  netlify/functions/save-discussion-background/helpers.ts
  netlify/functions/save-discussion-background/index.d.ts
  netlify/functions/save-discussion-background/index.ts
Labels: ready-to-merge

#1641 fix: updated april docs report due to Abhishek having to bow out
  pages/blog/2023-April-docs-report.md
Labels: ready-to-merge, gsod

#1638 chore: add the let keyword to this declaration of variables to make it explicit
  scripts/build-docs.js
  scripts/dashboard/build-dashboard.js
Labels: ready-to-merge

#1652 fix: make sure schema store rewriting supports $
  netlify/edge-functions/serve-definitions.ts
Labels: ready-to-merge

#1653 fix: make sure function for rewriting request supports %
  netlify/edge-functions/serve-definitions.ts
Labels: ready-to-merge

#1549 fix: fixed the contact page position
  pages/casestudies/[id].js
Labels: ready-to-merge

#1655 fix: better error handling for discussion saviour bot
  netlify/functions/save-discussion-background/Reposity.ts
  netlify/functions/save-discussion-background/Slack.ts
  netlify/functions/save-discussion-background/helpers.ts
  netlify/functions/save-discussion-background/index.ts
Labels: ready-to-merge

#1481 fix: remove modelina specific code from website
  package-lock.json
  package.json
  pages/tools/modelina.js
Labels: ready-to-merge

#1672 chore: update slack invite link
  public/_redirects
Labels: ready-to-merge

#1677 chore: add banner to promote CFP
  components/campaigns/AnnoucementHero.js
  pages/community/ambassadors/index.js
  pages/community/events/index.js
  pages/community/index.js
Labels: ready-to-merge

#1670 fix: blog page displays wrong list of articles first before displaying the correct articles #1603
  pages/blog/index.js
Labels: ready-to-merge

#1614 docs: fix navigation highlight issue in table of contents
  components/TOC.js
Labels: ready-to-merge

#1443 feat: introduce configurable `edit page on github` redirection
  components/layout/DocsLayout.js
  config/edit-page-config.json
  scripts/build-post-list.js
Labels: ready-to-merge

#1682 docs: updated cli docs 4 windows
  assets/docs/fragments/cli-installation.md
Labels: ready-to-merge

#1661 fix: refactored the hardcoded data of casestudy section
  pages/casestudies/[id].js
Labels: ready-to-merge

#1709 feat: adding cypress
  .eslintrc.js
  cypress.config.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/test/ComponentName.cy.js
  package-lock.json
  package.json
Labels: ready-to-merge, gsoc

#1631 fix: schema changed for language field
  scripts/tools/combine-tools.js
  scripts/tools/tools-schema.json
Labels: ready-to-merge
