Repository asyncapi/website, pull requests merged in 2024-02, with the labels that each got.

#2624 chore: configuring new finance year and adding latest data
  components/FinancialSummary/BarChartComponent.js
  config/finance/2023/Expenses.yml
  config/finance/2024/Expenses.yml
  config/finance/2024/ExpensesLink.yml
  lib/getUniqueCategories.js
  scripts/finance/index.js
Labels: ready-to-merge

#2637 fix: fixed typo in the MAINTAINERS.json file
  config/MAINTAINERS.json
Labels: ready-to-merge

#2245 docs: tutorial for WebSockets with AsyncAPI
  pages/docs/tutorials/websocket/_section.md
  pages/docs/tutorials/websocket/index.md
Labels: ready-to-merge

#2353 docs: tutorial for Request Reply using WebSockets with AsyncAPI
  pages/docs/tutorials/websocket/websocket-request-reply.md
Labels: ready-to-merge

#2252 docs: using AsyncAPI with Kafka
  pages/docs/tutorials/kafka/_section.md
  pages/docs/tutorials/kafka/index.md
Labels: ready-to-merge

#2329 docs: using AsyncAPI with Kafka using Avro
  pages/docs/tutorials/kafka/configure-kafka-avro.md
Labels: ready-to-merge

#2184 feat: enable i18n support for AsyncAPI website
  components/languageSelector/LanguageSelect.js
  components/link.js
  components/navigation/MenuBlocks.js
  components/navigation/NavBar.js
  lib/i18nPaths.js
  pages/index.js
Labels: autoupdate

#2130 docs: add translations guide for AsyncAPI website
  ADDING_TRANSLATIONS.md
Labels: ready-to-merge, autoupdate

#2644 docs: fixing docs bugs made by quetzalli
  pages/docs/tutorials/kafka/_section.md
  pages/docs/tutorials/kafka/index.md
  pages/docs/tutorials/websocket/index.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#2649 refactor: removed unnecessary packages and components
  components/JobSummary.js
  components/buttons/ApplyJob.js
  components/buttons/OpenInPlaygroundButton.js
  components/dashboard/table/Pagination.js
  components/footer/FooterList.js
  components/helpers/markdownToReact.js
  components/icons/Calendar copy.js
  components/icons/React.js
  components/icons/Tools.js
  components/illustrations/EveAndChan.js
  components/layout/GenericWideLayout.js
  components/layout/JobsLayout.js
  components/layout/Layout.js
  components/navigation/JobPostItem.js
  components/navigation/TutorialList.js
  components/tabs/Tabs.js
  context/JobsContext.js
  cypress/fixtures/jobpost.json
  cypress/fixtures/navigation-mock.js
  cypress/test/components/JobSummary.cy.js
  cypress/test/components/buttons/ApplyJob.cy.js
  cypress/test/components/buttons/OpenInPlaygroundButton.cy.js
  cypress/test/components/layout/JobsLayout.cy.js
  cypress/test/components/layout/Layout.cy.js
  cypress/test/components/navigation/JobPostItem.cy.js
  package-lock.json
  package.json
  pages/jobs/apiture-api-architect.md
  pages/jobs/dev-rel-postman.md
  pages/jobs/head-of-dx-upvest.md
  pages/jobs/index.js
  pages/jobs/tech-writer-postman.md
  pages/jobs/ui-ux-dx-designer.md
  pages/workshops/preregistration.js
  public/img/posts/june-2021-at-asyncapi/jobs.webp
  scripts/build-post-list.js
  scripts/index.js
Labels: ready-to-merge

#2705 chore: refresh sponsors list by adding Postman and HiveMQ
  components/sponsors/GoldSponsors.js
  components/sponsors/GoldSponsorsList.js
  components/sponsors/SilverSponsorsList.js
  components/sponsors/SponsorsList.js
  public/img/sponsors/hivemq_logo.png
Labels: ready-to-merge

#2699 chore: update test script in package.json
  package.json
Labels: ready-to-merge

#2474 docs: remove excess quotes in Restricted parameters object
  pages/docs/migration/migrating-to-v3.md
Labels: ready-to-merge

#2514 docs: removed redundant file `glee-auth`
  pages/docs/tools/glee/intro-auth.md
Labels: ready-to-merge, autoupdate

#2713 docs: add new adopters basing on content from AsyncAPI conferences
  config/adopters.yml
  cypress/test/components/CaseStudyCard.cy.js
Labels: ready-to-merge
