Repository asyncapi/website, pull requests merged in 2024-09, with the labels that each got.

#3164 chore: update finance report for june-july-august
  config/finance/2024/Expenses.yml
  config/finance/2024/ExpensesLink.yml
Labels: ready-to-merge

#3194 feat: update Slack Link
  public/_redirects
Labels: ready-to-merge

#3166 chore(blog): add august summary
  markdown/blog/2024-august-summary.md
  markdown/blog/2024-july-summary.md
  public/img/posts/2024-blog-banner/blog-banner-august.webp
Labels: ready-to-merge

#3076 feat: added tests for build-meetings.js
  scripts/build-meetings.js
  tests/build-meetings.test.js
  tests/fixtures/meetingsData.js
Labels: ready-to-merge, gsoc

#3111 fix: nexti18nSetup for OG tags error
  components/CaseStudyCard.tsx
  components/Head.tsx
  components/MDX/MDX.tsx
  components/MDX/MDXTable.tsx
  components/NewsletterSubscribe.tsx
  components/dashboard/Header.tsx
  components/link.tsx
  components/navigation/NavBar.tsx
  components/newsroom/FeaturedBlogPost.tsx
  markdown/blog/asyncapi-and-apicurio-for-asynchronous-apis.md
  markdown/blog/event-streaming-an-additional-architectural-style-to-suplement-api-design.md
  markdown/blog/status-update-27-20.md
  markdown/blog/websocket-part2.md
  markdown/docs/tools/cli/context.md
  mdx-components.tsx
  next-i18next-static-site.config.js
  next-i18next.config.js
  next.config.mjs
  package-lock.json
  package.json
  pages/[lang]/index.tsx
  pages/[lang]/tools/cli.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/casestudies/[id].tsx
  pages/index.tsx
  pages/tools/cli.tsx
  pages/tools/generator.tsx
  pages/tools/github-actions.tsx
  pages/tools/modelina.tsx
  pages/tools/parsers.tsx
  public/locales/de/common.json
  public/locales/de/landing-page.json
  public/locales/de/tools.json
  public/locales/en/common.json
  public/locales/en/landing-page.json
  public/locales/en/tools.json
  utils/browserLanguageDetector.ts
  utils/getStatic.ts
  utils/i18n.ts
  utils/i18n.tsx
  utils/i18nPaths.ts
  utils/languageDetector.ts
  utils/locales.ts
  utils/redirect.ts
  utils/staticHelpers.ts
Labels: bounty

#3201 fix: remove the jobs section from footer
  components/footer/FooterList.ts
Labels: ready-to-merge

#2493 test: add tests for netlify functions
  .github/workflows/netlify-edge-functions-test.yml
  jest.config.js
  netlify/edge-functions/serve-definitions.ts
  netlify/edge-functions/tests/serve-definitions.test.ts
  package.json
Labels: ready-to-merge

#3066 docs: replace incorrect mention of channels
  markdown/docs/concepts/asyncapi-document/structure.md
Labels: ready-to-merge

#3116 fix: links in tools section to specific category do not work
  components/tools/ToolsCard.tsx
  components/tools/ToolsDashboard.tsx
  components/tools/ToolsList.tsx
  types/components/tools/ToolDataType.ts
Labels: ready-to-merge

#3180 docs: add index.md for bindings folder
  assets/docs/fragments/bindings-overview.md
  markdown/docs/concepts/asyncapi-document/adding-bindings.md
  markdown/docs/reference/bindings/_section.md
  markdown/docs/reference/bindings/index.md
Labels: bounty

#3229 fix: netlify-edge-functions-test for PRs and jest tests
  .github/workflows/netlify-edge-functions-test.yml
  .gitignore
Labels: ready-to-merge

#3234 chore: add Ashmit Gupta as a code triager
  CODEOWNERS
Labels: ready-to-merge

#3232 fix: case study card linking to the wrong url
  components/CaseStudyCard.tsx
Labels: ready-to-merge

#3255 feat: extend paris banner
  components/campaigns/banners.ts
Labels: ready-to-merge

#3213 fix: modifying docker script for generating template
  components/GeneratorInstallation.tsx
Labels: ready-to-merge

#2687 refactor: update financial data for current year
  components/FinancialSummary/BarChartComponent.tsx
  components/FinancialSummary/Card.tsx
  components/FinancialSummary/ExpensesCard.tsx
  scripts/finance/index.js
  scripts/index.js
  tests/finance/index.test.js
  utils/getUniqueCategories.ts
Labels: ready-to-merge
