Repository asyncapi/website, pull requests merged in 2024-10, with the labels that each got.

#3245 feat: add tests for build tools script
  scripts/build-tools.js
  scripts/tools/combine-tools.js
  tests/build-tools.test.js
  tests/fixtures/buildToolsData.js
Labels: ready-to-merge, gsoc

#3137 feat: add test for build docs script
  scripts/build-docs.js
  tests/build-docs/addDocButtons.test.js
  tests/build-docs/buildNavTree.test.js
  tests/build-docs/convertDocPosts.test.js
  tests/fixtures/addDocButtonsData.js
  tests/fixtures/buildNavTreeData.js
  tests/fixtures/convertDocPostData.js
Labels: ready-to-merge, gsoc

#3269 docs: replace duplicated content with reusable fragments
  README.md
  assets/docs/fragments/contribution-notes.md
  assets/docs/fragments/how-to-contribute.md
  assets/docs/fragments/talk-to-me.md
  markdown/blog/2023-April-docs-report.md
  markdown/blog/2023-Q1-docs-report.md
  markdown/blog/2023-Q4-docs-report.md
  markdown/blog/2023-july-docs-report.md
  markdown/blog/2023-june-docs-report.md
  markdown/blog/2023-may-docs-report.md
  markdown/blog/changes-coming-docs.md
  markdown/blog/google-season-of-docs-2022.md
  markdown/docs/community/index.md
  markdown/docs/concepts/asyncapi-document/adding-bindings.md
  markdown/docs/concepts/index.md
  markdown/docs/guides/index.md
  markdown/docs/reference/bindings/index.md
  markdown/docs/reference/index.md
  markdown/docs/tools/index.md
  markdown/docs/tutorials/generate-code.md
  markdown/docs/tutorials/index.md
Labels: ready-to-merge

#3262 fix: remove hydration errors
  components/AlgoliaSearch.tsx
  components/Avatar.tsx
  components/Loader.tsx
  components/dashboard/table/Row.tsx
  components/navigation/BlogPostItem.tsx
  components/newsroom/FeaturedBlogPost.tsx
  components/tools/ToolsCard.tsx
  next-env.d.ts
  pages/blog/index.tsx
  pages/index.tsx
  utils/getStatic.ts
Labels: ready-to-merge

#3168 feat: add codecov to the project
  .github/workflows/if-nodejs-pr-testing.yml
  jest.config.js
Labels: ready-to-merge, gsoc

#3294 fix: updated CSS for tools/generator page buttons
  pages/tools/generator.tsx
Labels: ready-to-merge

#3304 fix: fixed dashboard scripts
  .github/workflows/regenerate-meetings-and-videos.yml
  components/newsroom/Newsroom.tsx
  scripts/dashboard/build-dashboard.js
Labels: ready-to-merge

#3301 test: add markdown tests
  .github/workflows/if-nodejs-pr-testing.yml
  markdown/docs/migration/index.md
  markdown/docs/migration/migrating-to-v3.md
  package.json
  scripts/markdown/check-markdown.js
Labels: bounty

#3319 fix: fixed rate limiting
  scripts/dashboard/build-dashboard.js
Labels: ready-to-merge

#3320 fix: fix testing workflow ref for branch pushes
  .github/workflows/if-nodejs-pr-testing.yml
Labels: ready-to-merge

#3327 fix: make the edit page on github point to correct resource
  config/edit-page-config.json
Labels: ready-to-merge

#3297 fix: file write errors for tools and newsroom video
  package-lock.json
  package.json
  scripts/build-newsroom-videos.js
  scripts/build-tools.js
  tests/build-newsroom-videos.test.js
  tests/build-tools.test.js
Labels: ready-to-merge

#3285 feat: exclude scripts with import errors
  jest.config.js
Labels: ready-to-merge, gsoc

#3312 feat: create banner for online conf
  components/campaigns/AnnouncementHero.tsx
  components/campaigns/banners.ts
Labels: ready-to-merge

#3338 chore: add Adidas and Morgan Stanley to list of adopters
  components/sponsors/SilverSponsorsList.ts
  config/adopters.yml
Labels: ready-to-merge

#3283 fix: wrong value of the enum in the tools-schema.json
  scripts/tools/tools-schema.json
Labels: ready-to-merge
