Repository asyncapi/website, pull requests merged in 2024-12, with the labels that each got.

#3443 chore: update slack invite link
  public/_redirects
Labels: ready-to-merge

#3265 feat: add tests for tool-object script
  scripts/tools/tools-object.js
  tests/helper/toolsObjectData.js
  tests/tools/tools-object.test.js
Labels: ready-to-merge, gsoc

#3136 feat: add test for combine tools script
  scripts/tools/combine-tools.js
  tests/fixtures/combineToolsData.js
  tests/fixtures/tools/automated-tools.json
  tests/fixtures/tools/manual-tools.json
  tests/tools/combine-tools.test.js
Labels: ready-to-merge, gsoc

#3447 fix: address search bar issue in the navbar
  components/AlgoliaSearch.tsx
Labels: ready-to-merge

#3456 refactor: removing non-breakable space #3455
  public/locales/en/landing-page.json
Labels: ready-to-merge

#3378 feat: add tests for check markdown script
  scripts/markdown/check-markdown.js
  tests/markdown/check-markdown.test.js
Labels: ready-to-merge

#3463 chore(blog): add last summary of the year
  markdown/blog/2024-december-and-paris.md
  markdown/blog/2024-october-summary.md
  public/img/posts/2024-blog-banner/blog-banner-december.webp
  public/img/posts/paris-conf-2024/annegret.webp
  public/img/posts/paris-conf-2024/frank.webp
  public/img/posts/paris-conf-2024/full-room.webp
  public/img/posts/paris-conf-2024/hari-and-joel.webp
  public/img/posts/paris-conf-2024/hugo.webp
  public/img/posts/paris-conf-2024/jonathan.webp
  public/img/posts/paris-conf-2024/julien-and-alessandro.webp
  public/img/posts/paris-conf-2024/laurent-and-hugo.webp
  public/img/posts/paris-conf-2024/leonid.webp
  public/img/posts/paris-conf-2024/lukasz-and-fran.webp
  public/img/posts/paris-conf-2024/naresh-and-pierre.webp
Labels: ready-to-merge

#3460 fix: fixed the notify triager workflow
  .github/workflows/notify-triager.yml
Labels: ready-to-merge, bounty

#3477 fix: bad token error of notify_triagers workflow
  .github/workflows/notify-triager.yml
Labels: ready-to-merge

#3419 refactor: removed unnecessary state use for hover effect
  pages/community/tsc.tsx
Labels: ready-to-merge

#3217 docs: broken link to generator github actions (Fixes #3190)
  markdown/blog/asyncapi-github-actions.md
  markdown/blog/status-update-47-20.md
Labels: ready-to-merge

#3459 chore(blog): google summer of code 2024 summary
  markdown/blog/2024-gsoc-wrap.md
  public/img/posts/gsoc.webp
Labels: ready-to-merge

#3442 fix: specification explorer layout issue by bumping schyma
  package-lock.json
  package.json
Labels: ready-to-merge

#3497 fix: #3496 text misalignment and unusual height reduction on hovering over boxes
  components/Asyncapi3Comparison/Asyncapi3IdAndAddressComparison.tsx
Labels: ready-to-merge

#3466 fix: resolved calender button render issue
  components/CommunityEvents.tsx
  components/Meeting.tsx
  pages/community/events/index.tsx
  utils/getStatic.ts
Labels: ready-to-merge

#3439 chore(blog): add marketing report
  markdown/blog/2024-marketing-report.md
  public/img/posts/marketing-images/buffer-report.webp
  public/img/posts/marketing-images/linkedIn-metrics-insights.webp
  public/img/posts/marketing-images/linkedin-performance-statistics.webp
  public/img/posts/marketing-images/marketing-wg.webp
  public/img/posts/marketing-images/merchandise.webp
  public/img/posts/marketing-images/store-report.webp
  public/img/posts/marketing-images/x-metrics-insights.webp
  public/img/posts/marketing-images/x-performance-statistics.webp
Labels: ready-to-merge

#3396 feat: added support for additional image formats in build-rss.js
  scripts/build-rss.js
Labels: ready-to-merge

#3284 feat: add tests for build post list script
  scripts/build-post-list.js
  scripts/index.js
  tests/build-post-list.test.js
  tests/fixtures/buildPostListData.js
  tests/helper/buildPostListSetup.js
  tests/index.test.js
Labels: ready-to-merge, gsoc

#3515 fix: testimonials alignment
  components/Testimonial.tsx
Labels: ready-to-merge

#3517 feat: increase code coverage
  jest.config.js
  scripts/build-pages.js
  tests/build-pages.test.js
  tests/dashboard/build-dashboard.test.js
  tests/index.test.js
Labels: ready-to-merge
