Repository asyncapi/website, pull requests merged in 2024-01, with the labels that each got.

#2423 feat: add message in-case there aren't any good first issues open
  components/dashboard/table/Table.js
Labels: ready-to-merge

#2520 docs: fix the bad link in Adopters section of Case studies page
  pages/casestudies/index.js
Labels: ready-to-merge

#2518 docs: fix the documentation link on landing page
  components/features/FeatureList.js
Labels: ready-to-merge

#2543 fix: edge function should not operate if not targeting definition files
  README.md
  netlify/edge-functions/serve-definitions.ts
Labels: ready-to-merge

#2532 fix: fixed a typo in hiring card of expenses breakdown section on finance page.
  components/FinancialSummary/ExpenseBreakdown.js
Labels: ready-to-merge, autoupdate

#2486 fix: Fixed the typo in Hiring card and added links to all Expenses Breakdown cards in Finance.
  components/FinancialSummary/ExpenseBreakdown.js
  components/footer/FooterList.js
Labels: ready-to-merge

#2536 style: feedback image sizing for <350px
  components/Feedback.js
Labels: ready-to-merge

#2466 fix: responsive button at up next button at docs/tools in overview page linked issue #2462
  components/buttons/DocsButton.js
Labels: ready-to-merge

#2509 style: enhanced spacing on tsc (Technical Steering Committee) page.
  pages/community/tsc.js
Labels: ready-to-merge

#2506 style: highlight the active link in menu
  components/navigation/MenuBlocks.js
Labels: ready-to-merge

#2277 feat: add dropdown for each section in navbar
  components/navigation/MobileNavMenu.js
  cypress/test/components/navigation/MobileNavMenu.cy.js
Labels: ready-to-merge

#2495 chore: removed redundant styling
  components/DemoAnimation.js
Labels: ready-to-merge

#2297 feat: added button that link to blog post in ambassador page
  pages/community/ambassadors/index.js
Labels: ready-to-merge

#2290 docs: add badges for social media profiles
  README.md
Labels: ready-to-merge

#2516 docs: update coming-from-openapi.md (#1951)
  pages/docs/tutorials/getting-started/coming-from-openapi.md
Labels: ready-to-merge

#2315 feat: add Mailchimp integration using netlify function
  README.md
  components/Loader.js
  components/NewsletterSubscribe.js
  config/mailchimp-config.json
  cypress/test/components/NewsletterSubscribe.cy.js
  locales/de/common.json
  locales/en/common.json
  netlify.toml
  netlify/functions/newsletter_subscription.js
  package-lock.json
  package.json
  pages/community/events/index.js
  pages/community/tsc.js
  styles/globals.css
Labels: ready-to-merge

#2572 chore(blog): adding Q4 docs report
  pages/blog/2023-Q4-docs-report.md
  pages/blog/2023-july-docs-report.md
  public/img/posts/2023-Q4-docs-report/Q4-docs-diagram-summary.webp
  public/img/posts/2023-Q4-docs-report/asyncapi-document-structure.webp
  public/img/posts/2023-Q4-docs-report/eve-chan.webp
Labels: ready-to-merge, 📑 docs, area/docs

#1874 chore(blog): add new blog about introduction to glee
  pages/blog/introduction-to-glee-a-spec-first-framework.md
  public/img/avatars/souvikns.webp
  public/img/posts/glee-banner.webp
  public/img/posts/glee-introduction/glee-file-structure.webp
  public/img/posts/glee-introduction/postman-glee-greet.webp
Labels: ready-to-merge

#2594 docs: add docs triagers to codeowners file
  CODEOWNERS
Labels: ready-to-merge, 📑 docs, area/docs

#2596 chore: add new CODEOWNERS
  CODEOWNERS
Labels: ready-to-merge

#2581 fix: fixed the design inconsistency issue in finance cards
  components/FinancialSummary/BarChartComponent.js
Labels: ready-to-merge

#2600 fix: centered the bar chart component
  components/FinancialSummary/BarChartComponent.js
Labels: ready-to-merge

#2549 chore(blog): annual review
  pages/blog/2023-summary.md
  pages/blog/september-2023.md
  public/img/posts/2023-summary/Issue-History.webp
  public/img/posts/2023-summary/NPM-packages.webp
  public/img/posts/2023-summary/Top-5-members.webp
  public/img/posts/2023-summary/Total-Contributors.webp
  public/img/posts/2023-summary/blog-banner-2023.webp
  public/img/posts/2023-summary/google-analytics.webp
  public/img/posts/2023-summary/google-console.webp
  public/img/posts/2023-summary/linkedin.webp
  public/img/posts/2023-summary/new-users-joining-per-year.webp
  public/img/posts/2023-summary/referred-by-LinkedIn.webp
  public/img/posts/2023-summary/referred-by-Twitter.webp
  public/img/posts/2023-summary/slack-activity.webp
  public/img/posts/2023-summary/success-sent.webp
  public/img/posts/2023-summary/total-opens.webp
  public/img/posts/2023-summary/unsubscribed.webp
  public/img/posts/2023-summary/youtube.webp
Labels: ready-to-merge

#2575 fix: applied the required changes Hiring card
  components/FinancialSummary/ExpenseBreakdown.js
Labels: ready-to-merge

#2539 feat: added finance and store to community
  cypress/test/pages/community/index.cy.js
  pages/community/index.js
Labels: ready-to-merge
