Repository asyncapi/website, pull requests merged in 2024-05, with the labels that each got.

#2931 feat: add london cfp banner
  components/campaigns/AnnoucementHero.js
Labels: ready-to-merge

#2943 chore: update finance info for february, march and april
  config/finance/2024/Expenses.yml
Labels: ready-to-merge

#2942 chore: update readme
  README.md
Labels: ready-to-merge

#2976 fix: fixed /docs/concepts/consumer page
  scripts/build-pages.js
Labels: ready-to-merge

#2974 chore: update CODEOWNERS docs triagers
  CODEOWNERS
Labels: ready-to-merge

#2966 docs: improve message.md
  pages/docs/concepts/message.md
Labels: 🐞 docs bug, area/docs

#2954 fix: banner button fixed
  components/campaigns/AnnoucementHero.js
Labels: ready-to-merge

#2986 fix: added more whiteList tags in build-pages
  scripts/build-pages.js
Labels: ready-to-merge

#2977 docs: vnk/fix websocket code snippet
  pages/docs/tutorials/websocket/index.md
Labels: ready-to-merge, 🐞 docs bug, area/docs

#2994 fix: successStories component in finance page
  components/FinancialSummary/SuccessStories.tsx
  components/data/successStoriesData.ts
  components/data/successStoriesData.tsx
Labels: ready-to-merge

#3004 fix: v3 specification reference section not loading during dev mode
  components/layout/DocsLayout.tsx
Labels: ready-to-merge
