Repository asyncapi/website, pull requests merged in 2024-08, with the labels that each got.

#3010 docs: case study from HDI Global SE
  config/casestudies/hdi.yml
  public/img/casestudies/hdi/hdi_logo.svg
  public/resources/casestudies/hdi/asyncapi.yaml
Labels: ready-to-merge

#3109 fix: component being rendered over the header
  components/campaigns/AnnouncementHero.tsx
Labels: ready-to-merge

#3077 fix: predefined bug port
  package.json
Labels: ready-to-merge

#3148 fix: create new package-lock.json and update nodejs workflow to use nvmrc
  .github/workflows/if-nodejs-pr-testing.yml
  .nvmrc
Labels: ready-to-merge

#3114 feat: added test for extract tools github
  scripts/tools/extract-tools-github.js
  tests/tools/extract-tools-github.test.js
Labels: ready-to-merge

#3093 feat: created input box component and stories for it
  components/InputBox.stories.tsx
  components/InputBox.tsx
  components/NewsletterSubscribe.tsx
  package-lock.json
  package.json
  types/components/FigurePropsType.ts
  types/components/InputBoxPropsType.ts
  types/components/community/CardPropsType.ts
  types/components/dashboard/TableTypes.ts
Labels: ready-to-merge, gsoc

#3095 chore: upgraded storybook from 8.1.11 to 8.2.4
  package-lock.json
  package.json
Labels: ready-to-merge, gsoc

#3075 feat: added tests for build-newsroom-videos.js
  package-lock.json
  package.json
  scripts/build-newsroom-videos.js
  tests/build-newsroom-videos.test.js
  tests/fixtures/newsroomData.js
Labels: ready-to-merge, gsoc

#3151 chore: add new sponsors to landing page
  components/sponsors/GoldSponsorsList.ts
  components/sponsors/SilverSponsors.tsx
  components/sponsors/SilverSponsorsList.ts
  components/sponsors/SponsorsList.ts
  public/img/sponsors/hdi_logo.png
  public/img/sponsors/route4me_logo.png
Labels: ready-to-merge

#3122 feat: added stories for blogs card
  components/navigation/BlogPostCard.stories.tsx
  components/navigation/BlogPostItem.tsx
Labels: ready-to-merge, gsoc

#3121 feat: create Accordion component and its stories
  components/Accordion/Accordion.stories.tsx
  components/Accordion/Accordion.tsx
  components/Accordion/AccordionItem.tsx
  components/MDX/MDX.tsx
  components/faq/FAQ.tsx
  components/faq/FAQList.tsx
  markdown/about/index.md
  types/components/AccordionItemType.ts
Labels: gsoc

#3082 feat: created toggle and checkbox components and added stories for them
  components/tools/Checkbox.stories.tsx
  components/tools/Checkbox.tsx
  components/tools/Filters.tsx
  components/tools/FiltersDropdown.tsx
  components/tools/Toggle.stories.tsx
  components/tools/Toggle.tsx
  package-lock.json
  types/components/tools/CheckboxPropsType.ts
  types/components/tools/TogglePropsType.ts
Labels: ready-to-merge, gsoc

#3123 feat: created loader component and added stories for it
  components/ClickableLogo.tsx
  components/Loader.stories.tsx
  components/Loader.tsx
  components/NewsletterSubscribe.tsx
  components/footer/Footer.tsx
  components/icons/AsyncAPIColorIcon.tsx
  components/icons/CircularLoader.tsx
  components/icons/Icons.mdx
  components/logos/AsyncAPILogo.tsx
  components/logos/AsyncAPILogoLight.tsx
  components/logos/logos.mdx
  components/navigation/MobileNavMenu.tsx
  components/navigation/NavBar.tsx
  components/tools/ToolsDashboard.tsx
  pages/index.tsx
Labels: ready-to-merge, gsoc

#3152 feat: configure storybook theme
  .storybook/AsyncAPIStorybookTheme.ts
  .storybook/manager.ts
  .storybook/preview.tsx
  public/img/logos/asyncapi-horizontal-logo.svg
  public/img/logos/asyncapi-horizontal-white-logo.svg
Labels: ready-to-merge, gsoc

#3163 fix: blog/websocket-part2 having rendering issues
  markdown/blog/websocket-part2.md
Labels: ready-to-merge

#2959 chore: introduce new contibutor guide with triagers and committers
  CONTRIBUTING.md
Labels: ready-to-merge
