Repository asyncapi/website, pull requests merged in 2024-03, with the labels that each got.

#2714 chore(blog): add february summary blog
  pages/blog/2024-february-summary.md
  public/img/posts/2024-blog-banner/blog-banner-february.webp
Labels: ready-to-merge

#2715 fix: unresponsive button at the tools/generator page linked issue #2464
  pages/tools/generator.js
Labels: ready-to-merge

#2718 fix: fixed the heights of buttons on tools/generator page
  pages/tools/generator.js
Labels: ready-to-merge

#2701 feat: migrate context
  context/AppContext.tsx
  context/BlogContext.tsx
  context/DocsContext.tsx
  context/GenericPostContext.tsx
  context/ToolFilterContext.tsx
  types/context/AppContext.ts
  types/context/DocsContext.ts
Labels: ready-to-merge

#2733 fix: space between search icon and i18n input options.
  components/navigation/NavBar.js
Labels: ready-to-merge

#2722 style: button and heading margin on tools/cli
  pages/[lang]/tools/cli.js
Labels: ready-to-merge

#2739 fix: fixed failing testcases of build-dashboard.cy.js
  cypress/test/scripts/dashboard/build-dashboard.cy.js
  scripts/dashboard/build-dashboard.js
Labels: ready-to-merge

#2563 fix: added links to all Expenses Breakdown cards in Finance.
  components/FinancialSummary/ExpenseBreakdown.js
Labels: ready-to-merge

#2712 fix: fixed schema declaration
  pages/docs/concepts/asyncapi-document/define-payload.md
Labels: ready-to-merge, autoupdate

#2734 feat: migrate newsroom components
  .eslintrc
  components/AuthorAvatars.tsx
  components/navigation/BlogPostItem.tsx
  components/newsroom/FeaturedBlogPost.tsx
  components/newsroom/Newsroom.tsx
  components/newsroom/NewsroomArticle.tsx
  components/newsroom/NewsroomBlogPosts.tsx
  components/newsroom/NewsroomSection.tsx
  components/newsroom/NewsroomYoutube.tsx
  components/newsroom/YouTubeCard.tsx
  components/newsroom/swiper.tsx
  netlify.toml
  package-lock.json
  package.json
  types/components/navigation/BlogPostType.ts
Labels: ready-to-merge

#2752 feat: migrate algolia search
  components/AlgoliaSearch.tsx
  package-lock.json
  pages/_app.tsx
  pages/index.tsx
Labels: ready-to-merge

#2728 style: casestudy page horizontal spacing
  pages/casestudies/[id].js
Labels: ready-to-merge

#2762 chore: update conference details
  cypress/test/pages/community/events/index.cy.js
  pages/community/events/index.js
  public/img/logos/confLogo.png
  public/img/logos/confLogo.webp
Labels: ready-to-merge

#2757 feat: migrate sponsors and support us components to typescript
  components/SupportUs/SupportItemsList.ts
  components/SupportUs/SupportUs.tsx
  components/sponsors/GoldSponsors.tsx
  components/sponsors/GoldSponsorsList.ts
  components/sponsors/SilverSponsors.tsx
  components/sponsors/SilverSponsorsList.ts
  components/sponsors/Sponsors.tsx
  components/sponsors/SponsorsList.ts
  types/components/sponsors/SponsorType.d.ts
Labels: ready-to-merge

#2776 fix: fix type error of the migrate-ts branch
  components/AlgoliaSearch.tsx
Labels: ready-to-merge

#2331 docs: tutorial for managing schemas with Schema Registry
  pages/docs/tutorials/kafka/managing-schemas-using-schema-registry.md
Labels: ready-to-merge

#2318 docs: tutorial for bindings with Kafka
  pages/docs/tutorials/kafka/bindings-with-kafka.md
Labels: ready-to-merge

#2763 feat: migrate logos, slack and roadmap components to typescript
  components/Modal.tsx
  components/logos/Adidas.tsx
  components/logos/Axway.tsx
  components/logos/SAP.tsx
  components/logos/Salesforce.tsx
  components/logos/Slack.tsx
  components/roadmap/RoadmapColumn.tsx
  components/roadmap/RoadmapItem.tsx
  components/roadmap/RoadmapList.tsx
  components/roadmap/RoadmapPill.tsx
  components/slack/Message.tsx
  components/slack/index.tsx
Labels: ready-to-merge

#2660 fix: add workflow to notify docs triagers on relevant PRs
  .github/workflows/notify-triager.yml
  CODEOWNERS
Labels: ready-to-merge

#2735 feat: migrate docs, data, and editor components to typescript
  components/Caption.tsx
  components/data/buckets.ts
  components/docs/Card.tsx
  components/docs/DocsCards.tsx
  components/editor/CodeBlock.tsx
  package-lock.json
  package.json
  tsconfig.json
  types/components/IconType.ts
Labels: autoupdate

#2669 fix: added the hover affect to icons
  components/icons/Github.js
  components/icons/LinkedIn.js
  components/icons/Twitter.js
  pages/community/tsc.js
  pages/tools/generator.js
  tailwind.config.js
Labels: ready-to-merge

#2799 feat: migrate leftover components
  components/AsyncAPILogo.tsx
  components/Calendar.tsx
  components/CaseStudyCard.tsx
  components/ClickableLogo.tsx
  components/DemoAnimation.tsx
  components/Feedback.tsx
  components/MacWindow.tsx
  package-lock.json
  package.json
  types/event.ts
  types/post.ts
Labels: ready-to-merge

#2807 feat: add prettier rules in eslint
  .eslintrc
  .prettierignore
  .prettierrc.json
  components/AlgoliaSearch.tsx
  components/AsyncAPILogo.tsx
  components/Calendar.tsx
  components/Caption.tsx
  components/CaseStudyCard.tsx
  components/ClickableLogo.tsx
  components/DemoAnimation.tsx
  components/Feedback.tsx
  components/FinancialSummary/BarChartComponent.tsx
  components/MacWindow.tsx
  components/Modal.tsx
  components/SupportUs/SupportItemsList.ts
  components/SupportUs/SupportUs.tsx
  components/buttons/DocsButton.tsx
  components/buttons/OpenInStudioButton.tsx
  components/buttons/ScrollButton.tsx
  components/community/Card.tsx
  components/community/Header.tsx
  components/community/Hero.tsx
  components/community/HomeCard.tsx
  components/data/buckets.ts
  components/data/otherFormsData.ts
  components/docs/Card.tsx
  components/docs/DocsCards.tsx
  components/editor/CodeBlock.tsx
  components/logos/Axway.tsx
  components/logos/SAP.tsx
  components/logos/Salesforce.tsx
  components/logos/Slack.tsx
  components/navigation/BlogPostItem.tsx
  components/newsroom/FeaturedBlogPost.tsx
  components/roadmap/RoadmapColumn.tsx
  components/slack/Message.tsx
  components/slack/index.tsx
  components/sponsors/GoldSponsors.tsx
  components/sponsors/SilverSponsors.tsx
  components/sponsors/SilverSponsorsList.ts
  components/sponsors/Sponsors.tsx
  components/sponsors/SponsorsList.ts
  components/typography/TextLink.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
Labels: ready-to-merge

#2769 feat: migrate asyncapi3comparison and tabs
  components/Asyncapi3Comparison/Asyncapi3ChannelComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3IdAndAddressComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3MetaComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3OperationComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3ParameterComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3SchemaFormatComparison.tsx
  components/Asyncapi3Comparison/Asyncapi3ServerComparison.tsx
  components/tabs/Tabs.tsx
Labels: ready-to-merge

#2801 feat: migrating remaining components to typescript
  components/Caption.tsx
  components/Figure.tsx
  components/Loader.tsx
  components/Profiles.tsx
  components/Remember.tsx
  components/Warning.tsx
  types/components/FigurePropsType.ts
Labels: ready-to-merge

#2785 feat: migrate open api comparison
  components/OpenAPIComparison.tsx
  components/OpenAPIComparisonV3.tsx
Labels: ready-to-merge

#2743 feat: migrate layout and campaigns
  components/AuthorAvatars.tsx
  components/Head.tsx
  components/TOC.tsx
  components/campaigns/AnnouncementBanner.tsx
  components/campaigns/AnnouncementHero.tsx
  components/campaigns/AnnouncementRemainingDays.tsx
  components/campaigns/Banner.tsx
  components/campaigns/banners.ts
  components/layout/BlogLayout.tsx
  components/layout/Column.tsx
  components/layout/Container.tsx
  components/layout/GenericLayout.tsx
  components/layout/GenericPostLayout.tsx
  components/layout/GenericWideLayout.tsx
  components/layout/Layout.tsx
  components/layout/Row.tsx
  context/BlogContext.tsx
  context/DocsContext.tsx
  context/GenericPostContext.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
Labels: ready-to-merge

#2765 feat: migrate navigation
  components/ClickableLogo.tsx
  components/data/buckets.ts
  components/docs/Card.tsx
  components/docs/DocsCards.tsx
  components/form/Select.tsx
  components/helpers/applyFilter.ts
  components/helpers/is-mobile.ts
  components/helpers/use-outside-click.tsx
  components/icons/SearchIcon.tsx
  components/languageSelector/LanguageSelect.tsx
  components/link.tsx
  components/navigation/BlogPostItem.tsx
  components/navigation/CommunityPanel.tsx
  components/navigation/DocsMobileMenu.tsx
  components/navigation/DocsNav.tsx
  components/navigation/DocsNavItem.tsx
  components/navigation/EventFilter.tsx
  components/navigation/EventPostItem.tsx
  components/navigation/Filter.tsx
  components/navigation/FlyoutMenu.tsx
  components/navigation/Label.tsx
  components/navigation/LearningPanel.tsx
  components/navigation/MenuBlocks.tsx
  components/navigation/MobileNavMenu.tsx
  components/navigation/NavBar.tsx
  components/navigation/NavItem.tsx
  components/navigation/NavMenu.tsx
  components/navigation/StickyNavbar.tsx
  components/navigation/SubCategoryDocsNav.tsx
  components/navigation/ToolsPanel.tsx
  components/navigation/TutorialList.tsx
  components/navigation/communityItems.tsx
  components/navigation/learningItems.tsx
  components/navigation/otherItems.tsx
  components/navigation/toolingItems.tsx
  components/newsroom/FeaturedBlogPost.tsx
  context/DocsContext.tsx
  package-lock.json
  package.json
  types/context/DocsContext.ts
  utils/i18nPaths.ts
Labels: ready-to-merge

#2774 feat: migrate tools components to typescript
  components/tools/CardData.tsx
  components/tools/CategoryDropdown.tsx
  components/tools/Filters.tsx
  components/tools/FiltersDisplay.tsx
  components/tools/FiltersDropdown.tsx
  components/tools/Tags.tsx
  components/tools/ToolsCard.tsx
  components/tools/ToolsDashboard.tsx
  components/tools/ToolsList.tsx
  scripts/tools/categorylist.js
  types/components/tools/ToolDataType.ts
Labels: ready-to-merge

#2806 fix: updated docTriagers and triager workflow
  .github/workflows/notify-triager.yml
  CODEOWNERS
Labels: ready-to-merge
