Repository asyncapi/website, pull requests merged in 2024-07, with the labels that each got.

#3012 feat: write tests and refactor scripts
  jest.config.js
  scripts/adopters/index.js
  scripts/finance/index.js
  scripts/utils.js
  scripts/utils/readAndWriteJson.js
  tests/adopters/index.test.js
  tests/fixtures/utilsData.js
  tests/readAndWriteJson.test.js
  tests/utils.test.js
Labels: ready-to-merge, gsoc

#3057 chore(blog): add june community summary blog
  markdown/blog/2024-june-summary.md
  markdown/blog/2024-may-summary.md
  public/img/posts/2024-blog-banner/blog-banner-june.webp
Labels: ready-to-merge

#3059 fix: fixed the issue of articles looking broken
  markdown/blog/2024-february-summary.md
  markdown/blog/conference-2022.md
  markdown/blog/hacktoberfest-2022.md
Labels: ready-to-merge

#3015 feat: storybook setup, chromatic setup and typography stories
  .eslintrc
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  README.md
  components/typography/Heading.stories.tsx
  components/typography/Heading.tsx
  components/typography/Paragraph.stories.tsx
  components/typography/Paragraph.tsx
  package-lock.json
  package.json
Labels: ready-to-merge, gsoc

#3014 fix: removed flickering effect in navbar for small devices
  components/navigation/MobileNavMenu.tsx
Labels: ready-to-merge

#3078 feat: added stories for icons, logos, and colors
  .gitignore
  .storybook/main.ts
  components/Colors.mdx
  components/Testimonial.tsx
  components/icons/Ambassador.tsx
  components/icons/Icons.mdx
  components/icons/Plant.tsx
  components/icons/Quote.tsx
  components/logos/logos.mdx
  components/navigation/communityItems.tsx
Labels: ready-to-merge

#3079 feat: add stories buttons
  components/buttons/Button.stories.tsx
  components/buttons/Button.tsx
  components/buttons/GithubButton.tsx
  components/buttons/GoogleCalendarButton.tsx
  components/buttons/ICSFileButton.tsx
  components/buttons/SlackButton.tsx
  components/buttons/SubscribeButton.tsx
  components/buttons/YoutubeButton.tsx
  types/components/buttons/ButtonPropsType.ts
  types/components/buttons/types.ts
Labels: ready-to-merge, gsoc

#3081 feat: created tags and avatar components and added stories for them
  components/AuthorAvatars.tsx
  components/Avatar.stories.tsx
  components/Avatar.tsx
  components/tools/Tags.stories.tsx
  components/tools/Tags.tsx
Labels: ready-to-merge, gsoc

#3084 fix: update CODEOWNERS
  CODEOWNERS
Labels: ready-to-merge

#3037 feat: add tests for finace and case studies
  scripts/casestudies/index.js
  scripts/finance/index.js
  scripts/index.js
  tests/casestudies/index.test.js
  tests/finance/index.test.js
  tests/fixtures/caseStudyData.js
  tests/fixtures/financeData.js
Labels: ready-to-merge, gsoc

#3038 fix: add node-fetch v2 for script automation and keep node-fetch v3
  package-lock.json
  package.json
  scripts/build-newsroom-videos.js
Labels: ready-to-merge, autoupdate

#3098 feat: update banner for paris conference
  components/campaigns/banners.ts
Labels: ready-to-merge

#3065 docs: update bump.sh tool card
  config/tools-manual.json
Labels: ready-to-merge

#3112 fix: front page alignment
  components/campaigns/AnnouncementHero.tsx
Labels: ready-to-merge

#2770 feat: add rendering of case study asyncapi document
  components/helpers/read-yaml-file.js
  components/helpers/read-yaml-file.ts
  pages/casestudies/[id].tsx
  utils/staticHelpers.ts
Labels: ready-to-merge

#3051 fix: blog landing page having problem with showing 2 authors names
  components/campaigns/AnnouncementHero.tsx
  components/helpers/read-yaml-file.js
  components/navigation/BlogPostItem.tsx
  pages/casestudies/[id].tsx
Labels: ready-to-merge
