Repository asyncapi/website, pull requests merged in 2025-08, with the labels that each got.

#4293 fix: revert ci workflows
  .github/workflows/if-nodejs-pr-testing.yml
Labels: autoupdate

#4192 refactor: created npm folder and modularized scripts
  .eslintignore
  .eslintrc
  jest.config.js
  mdx-components.tsx
  npm/runners/build-adopters-list-runner.ts
  npm/runners/build-dashboard-runner.ts
  npm/runners/build-finance-info-list-runner.ts
  npm/runners/build-meetings-runner.ts
  npm/runners/build-newsroom-videos-runner.ts
  npm/runners/build-pages-runner.ts
  npm/runners/build-post-list-runner.ts
  npm/runners/build-tools-runner.ts
  npm/runners/case-studies-runner.ts
  npm/runners/compose-blog-runner.ts
  package-lock.json
  package.json
  scripts/adopters/index.ts
  scripts/build-meetings.ts
  scripts/build-newsroom-videos.ts
  scripts/build-pages.ts
  scripts/build-post-list.ts
  scripts/build-rss.ts
  scripts/build-tools.ts
  scripts/casestudies/index.ts
  scripts/compose.ts
  scripts/dashboard/build-dashboard.ts
  scripts/finance/index.ts
  scripts/helpers/check-locales.ts
  scripts/helpers/logger.ts
  scripts/helpers/readAndWriteJson.ts
  scripts/index.ts
  scripts/markdown/check-edit-links.ts
  scripts/markdown/check-markdown.ts
  scripts/tools/categorylist.ts
  scripts/tools/combine-tools.ts
  scripts/tools/extract-tools-github.ts
  scripts/tools/tools-object.ts
  tests/adopters/index.test.ts
  tests/build-meetings.test.ts
  tests/build-pages.test.ts
  tests/build-rss.test.ts
  tests/build-tools.test.ts
  tests/casestudies/index.test.ts
  tests/check-locales.test.js
  tests/check-locales.test.ts
  tests/dashboard/build-dashboard.test.ts
  tests/finance/index.test.ts
  tests/fixtures/combineToolsData.ts
  tests/markdown/check-markdown.test.ts
  tests/tools/combine-tools.test.ts
  tests/tools/tools-object.test.ts
  types/components/AccordionItemType.ts
  types/components/IconType.ts
  types/components/tools/TogglePropsType.ts
  types/components/tools/ToolDataType.ts
  types/context/AppContext.ts
  types/errors/CustomError.ts
  types/pages/community/Community.ts
  types/typography/Heading.ts
  types/typography/Paragraph.ts
Labels: ready-to-merge, do-not-merge, gsoc, autoupdate

#3411 docs: improve writing style for tags
  markdown/docs/concepts/asyncapi-document/tags.md
Labels: ready-to-merge, 📑 docs, area/docs

#4287 chore(blog): add the july community summary
  components/campaigns/banners.ts
  markdown/blog/2025-july-summary.md
  markdown/blog/2025-may-summary.md
  markdown/blog/first-governance-elections.md
  next-env.d.ts
  package-lock.json
  public/img/posts/2025-blog-banner/banner-july.webp
  public/img/posts/lagos-conf/ace-thulie.webp
  public/img/posts/lagos-conf/ace.webp
  public/img/posts/lagos-conf/booth-duty.webp
  public/img/posts/lagos-conf/booth-munich.webp
  public/img/posts/lagos-conf/booth-pic.webp
  public/img/posts/lagos-conf/maya.webp
  public/img/posts/lagos-conf/prince.webp
  public/img/posts/lagos-conf/thulie.webp
Labels: ready-to-merge

#4365 fix: update slack invite url
  public/_redirects
Labels: ready-to-merge
