Repository asyncapi/website, pull requests merged in 2025-04, with the labels that each got.

#3883 refactor: add missing templates manually and remove duplicates from automation
  config/generator-templates.json
  config/tools-manual.json
Labels: ready-to-merge

#3976 feat: add venue cfp banners
  components/campaigns/AnnouncementHero.tsx
  components/campaigns/banners.ts
Labels: ready-to-merge

#3966 chore(blog): add the march summary
  markdown/blog/2025-february-summary.md
  markdown/blog/2025-march-summary.md
  markdown/blog/release-notes-3.0.0.md
  public/img/posts/2025-blog-banner/banner-march.webp
Labels: ready-to-merge

#4013 fix: banner overlapping with Navbar
  components/campaigns/AnnouncementBanner.tsx
  components/campaigns/AnnouncementHero.tsx
  components/icons/ArrowLeft.tsx
Labels: ready-to-merge

#3492 fix: add visual on the generators
  pages/tools/generator.tsx
  public/img/diagrams/generator.webp
Labels: ready-to-merge, area/design

#3805 fix: centered card in casestudies page
  components/CaseStudyCard.tsx
Labels: ready-to-merge

#4028 chore: update slack invite link
  public/_redirects
Labels: ready-to-merge

#3531 fix: wrong type of payload and headers in MessageExample
  markdown/docs/reference/specification/v3.0.0.md
Labels: ready-to-merge

#4039 fix: conference date alignment in sequence
  components/campaigns/banners.ts
Labels: ready-to-merge

#3738 fix: enable titleView for dropdown menu in mobile view
  components/layout/DocsLayout.tsx
Labels: ready-to-merge

#3950 feat: add check-locales workflow
  .github/workflows/if-nodejs-pr-testing.yml
  package.json
  scripts/utils/check-locales.ts
  tests/check-locales.test.js
Labels: ready-to-merge, bounty

#3420 docs(tutorials): fix indentation for slackbot with websocket doc
  markdown/docs/tutorials/websocket/index.md
Labels: ready-to-merge, 📑 docs, area/docs

#4049 feat: add development setup related files
  components/navigation/MobileNavMenu.tsx
  development/scripts/build-docs.md
  development/scripts/build-meetings.md
  development/scripts/build-newsroom-videos.md
  development/scripts/build-pages.md
  development/scripts/build-rss.md
  development/scripts/build-tools.md
  development/vscode/launch.sample.json
  package.json
  scripts/adopters/index.ts
  scripts/build-meetings.ts
  scripts/build-newsroom-videos.ts
  scripts/build-tools.ts
  scripts/casestudies/index.ts
  scripts/compose.ts
  scripts/dashboard/build-dashboard.ts
  scripts/finance/index.ts
  scripts/helpers/check-locales.ts
  scripts/helpers/logger.ts
  scripts/helpers/readAndWriteJson.ts
  scripts/helpers/utils.ts
  scripts/markdown/check-edit-links.ts
  scripts/markdown/check-markdown.ts
  scripts/tools/combine-tools.ts
  scripts/tools/extract-tools-github.ts
  scripts/tools/tools-object.ts
  tests/adopters/index.test.js
  tests/check-locales.test.js
  tests/dashboard/build-dashboard.test.js
  tests/markdown/check-edit-links.test.js
  tests/markdown/check-markdown.test.js
  tests/readAndWriteJson.test.js
  tests/tools/combine-tools.test.js
  tests/tools/extract-tools-github.test.js
  tests/tools/tools-object.test.js
  tests/utils.test.js
Labels: ready-to-merge, autoupdate, bounty
