Repository asyncapi/website, pull requests merged in 2025-02, with the labels that each got.

#3634 fix: remove commas from fragment URLs
  components/TOC.tsx
Labels: ready-to-merge

#3624 fix: remove shop link from the footer section
  components/footer/FooterList.ts
Labels: ready-to-merge

#3662 ci: testing of automerge changes
  .github/workflows/automerge-for-humans-merging.yml
Labels: ready-to-merge, autoupdate

#3556 feat: enabling i18n feature for smaller screens
  ADDING_TRANSLATIONS.md
  components/icons/Icons.mdx
  components/icons/Language.tsx
  components/languageSelector/LanguageSelect.tsx
  components/navigation/MobileNavMenu.tsx
  components/navigation/NavBar.tsx
  next-i18next.config.js
Labels: ready-to-merge, bounty

#3675 docs: add Rohit as core docs maintainer and Prince as docs triager
  CODEOWNERS
Labels: ready-to-merge

#3735 chore(blog): add february summary
  markdown/blog/2024-annual-summary.md
  markdown/blog/2025-february-summary.md
  markdown/blog/conference-2024-summary.md
  public/img/posts/2025-blog-banner/banner-february.webp
  public/img/posts/2025-blog-banner/voting-example.webp
Labels: ready-to-merge
