Repository asyncapi/website, pull requests merged in 2025-01, with the labels that each got.

#3561 fix: #3544 Misalignment of Height and Spacing in Case Study Block on Desktop and Mobile Views.
  components/CaseStudyCard.tsx
Labels: ready-to-merge

#3480 fix: component CodeBlock not able to highlight lines.
  components/editor/CodeBlock.tsx
Labels: ready-to-merge

#3557 feat: add workflow and script to check edit links on docs
  .github/workflows/check-edit-links.yml
  components/layout/DocsLayout.tsx
  config/edit-page-config.json
  jest.config.js
  package.json
  scripts/dashboard/build-dashboard.js
  scripts/markdown/check-edit-links.js
  tests/fixtures/markdown/check-edit-links-data.js
  tests/markdown/check-edit-links.test.js
Labels: ready-to-merge, bounty

#3555 docs(tutorials): fixes #3550
  markdown/docs/tutorials/kafka/index.md
Labels: 📑 docs, area/docs

#3599 fix: removed the swags and goodies card
  pages/community/index.tsx
Labels: ready-to-merge

#3578 chore(blog): add the 2024 annual report
  markdown/blog/2024-annual-summary.md
  markdown/blog/2024-december-and-paris.md
  markdown/blog/2024-marketing-report.md
  public/img/posts/2024-annual-report/blog-banner.webp
  public/img/posts/2024-annual-report/google-analytics.webp
  public/img/posts/2024-annual-report/google-search-console.webp
  public/img/posts/2024-annual-report/issues.webp
  public/img/posts/2024-annual-report/linkedin-followers.webp
  public/img/posts/2024-annual-report/new-slack-users.webp
  public/img/posts/2024-annual-report/npm-packages.webp
  public/img/posts/2024-annual-report/slack-top-five.webp
  public/img/posts/2024-annual-report/total-contributors.webp
  public/img/posts/2024-annual-report/total-opens-newsletter.webp
  public/img/posts/2024-annual-report/visits-from-linkedin.webp
  public/img/posts/2024-annual-report/visits-from-newsletter.webp
  public/img/posts/2024-annual-report/visits-from-twitter.webp
  public/img/posts/2024-annual-report/weekly-slack-activity.webp
  public/img/posts/2024-annual-report/youtube-stats.webp
Labels: ready-to-merge

#3519 feat: optimize banner rendering performance
  components/campaigns/AnnouncementHero.tsx
Labels: ready-to-merge

#3562 fix: toc links in the blogs
  components/TOC.tsx
Labels: ready-to-merge

#3615 chore: update slack invite link
  public/_redirects
Labels: ready-to-merge

#3605 feat: make scroll to top button attractive with hover effects
  components/buttons/ScrollButton.tsx
Labels: ready-to-merge

#3620 feat: add Singapore banner
  components/campaigns/banners.ts
Labels: ready-to-merge
